### ISSUE TITLE
Trade history view for the market activities

### ISSUE THREAD

**Issue by Freakazoid78tr** [BibliothecaDAO/eternum#1015]
A history of what a player sold for how much, through the market would be nice. Maybe a general order history for the market per resource  that one can filter by resource or even by their own trades would be very useful. That way players can see what is selling at what price and add more liquidity to the market which could help everyone in the game. Currently, you can see that you are receiving some lords but you don't know from what trade you earned that lords. More data can help increase market liquidity which is critical for trade to flourish.

**Comment by aymericdelab** [comment]
fixed by @edisontim in #1043
