### ISSUE TITLE
[client] feat: next iteration of order book

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1017]
For the next iteration of the order book, we should allow users to purchase incremental parts of the order. This requires discussion and will happen after the AMM is working as expected.

What this means:

**Order:**
100,000 Stone @ 0.1 Lords

Anyone come and purchase any quantity of the 100,000 lords. 

**Benefit**
It means you can purcahse exactly what you want, rather than a huge amount. And for sellers you only have to make 1 big order, rather than splitting it up. This will increase the velocity of trading.

**Comment by aymericdelab** [comment]
separated into #1214 and #1213
