### ISSUE TITLE
[contract] claim starting resources

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1036]
The amount of resources claimable should depend on the resources you produce on your realm:

- lords, troops, donkeys, wheat and fish stay the same
- other resources should be claimable depending on the input resources needed to start production on your realm:
-    base amount: X, for resources not needed to produce on your realm, could be set very low or even to 0
-    production amount: Y, for resources needed as input for production on your realm

1. keep the mint config so that you can still add arbitrary amounts/resourceids to the claimable resources for lords, troops, food and donkeys
2. add additional base amount and production amount in mint config.
3. change the mint_starting_resources function to also retrieve the inputs needed for production for the realm

**Comment by aymericdelab** [comment]
working on it

**Comment by aymericdelab** [comment]
currently done in a naive way by minting the resources directly in the wallet. If we keep this resource allocation strategy, we should add in the contract.

**Comment by edisontim** [comment]
Can this be closed?
