### ISSUE TITLE
[Client + Contract] If your realm defender army gets defeated, its resources remain locked

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1068]
In a scenario where a defender army of a realm gets defeated, and the attacker leaves the battle, you cannot make the defending army leave from the client. Resources of the realm remain locked and you cannot deposit to it either.

1. Create defender army for realm A
2. Attack realm A with bigger army from realm B
3. realm B army leaves battle
4. Attempt to deposit resources with another realm A army to realm A

**Comment by edisontim** [comment]
Closed by #1086
