### ISSUE TITLE
feat: add an incentive to claim a hyperstructure

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1088]
Currently, there's no incentive to stealing a hyperstructure. The points are still being distributed to the original contributors, so no the owner doesn't get a bonus of any sorts.

Potential ideas: 
- Allow owner to whitelist people to contribute to a hyperstructure
- Give a point bonus to owner

**Comment by ponderingdemocritus** [comment]
isn't the incentive the hyperstructure itself? As the hyperstructure stands it generates points. If you claim it you shoul dbe able to destroy it.

**Comment by edisontim** [comment]
Duplicate issue, will close this one and leave #1123 open
