### ISSUE TITLE
[client] z-index on army pannel

### ISSUE THREAD

**Issue by Bal7hazar** [BibliothecaDAO/eternum#1090]
**Describe the bug** A clear and concise description of what the bug is.

![image](https://github.com/BibliothecaDAO/eternum/assets/97087040/94dadaf3-c1b5-422c-836e-e4f24d0e9315)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 126.0.6478.127 (Build officiel) (arm64)

**Comment by ponderingdemocritus** [comment]
superseded by new v
