### ISSUE TITLE
Dead armies walking…

### ISSUE THREAD

**Issue by Freakazoid78tr** [BibliothecaDAO/eternum#1093]
I had a few armies testing to capture the fragment mine from the mercenaries. A few of my armies died by going down to zero military unit in them. But once I won the battle, I had all of the armies leave the battlefield. It looks like, even the dead armies can come out if the battlefield and you can move them around on the map. 

![image](https://github.com/BibliothecaDAO/eternum/assets/102276968/413fa55f-5785-4429-b146-470c27ed3161)

**Comment by edisontim** [comment]
Will leave open but should be fixed in my latest PR

**Comment by aymericdelab** [comment]
should be fixed once #1127 is completed

**Comment by edisontim** [comment]
Will close as this hasn't been happening again
