### ISSUE TITLE
[client] Can't leave battle with mercenaries

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1094]
<img width="539" alt="Screenshot 2024-07-07 at 12 55 55" src="https://github.com/BibliothecaDAO/eternum/assets/76473430/4695c3b9-9777-4f5c-b891-3d729f4cf920">

**Comment by ponderingdemocritus** [comment]
is this done @credence0x ?

**Comment by aymericdelab** [comment]
@credence0x can you tackle this ?
