### ISSUE TITLE
Game crash - if you click 'battle details' on battle page

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1101]
and click 'battle details' on the lozenge in the middle - 
<img width="1440" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/102318873/dba64076-f61b-44e2-a436-3f890cd8b146">
it crashes the game - white screen

<img width="1440" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/102318873/61d703f6-f8e8-484e-acd9-9383403bedad">

**Comment by edisontim** [comment]
Thanks for raising the issue, do you remember what actions you took before this?

**Comment by credence0x** [comment]
@edisontim  go to Niksu, click on the battle happening there, then click `Battle Details`. I own Niksu. what happened was i withdrew my Realm's Army from a battle i had already won. So there is no battle going on but the battle icon is still showing.

**Comment by edisontim** [comment]
@credence0x ok ok, was your army the defending army?

**Comment by edisontim** [comment]
Will leave open but should be fixed in my latest PR

**Comment by aymericdelab** [comment]
is this fixed? @edisontim

**Comment by edisontim** [comment]
Haven't has this happen again so will close
