### ISSUE TITLE
[client]: forbid an army from joining a battle if he already has an army on either side

### ISSUE THREAD

**Issue by credence0x** [BibliothecaDAO/eternum#1127]

**Comment by edisontim** [comment]
Rationale behind this is:
- Losers of a battle do not have an incentive of leaving a battle, except if they reach the limit of their armies, but for people stopping playing or people that never reach their limit they won't delete the losing armies.
- If a lot of people leave dead armies in battle it will accumulate, cause clutter and filtering on the client that might add some heavy load

One solution to this is making the losing armies leave a battle automatically. This can be done multiple ways:
- Make the first winner leaving delete all the losing armies (will be cost heavy for him)
- Make each winner delete `nbr_defender_armies / nbr_attacker_armies` to split the costs
- Keep a portion of the battle chest (3-4%) for the person deleting the losers

For these solutions, in any ways we need to avoid having the costs ramp up, so we might need to limit the number of armies on each side of the battle.

If we do this, we need to avoid having someone placing armies of one unit in the opposing side of his battle to block the opponent from getting reinforcement

**Comment by aymericdelab** [comment]
you can delete an entity in torii by emitting an event like this one:

```
#[derive(Drop, starknet::Event)]
    pub struct StoreDelRecord {
        pub table: felt252,
        pub entity_id: felt252,
    }
```

**Comment by aymericdelab** [comment]
@edisontim is this still needed ?

**Comment by edisontim** [comment]
I think this isn't needed, we've seen that client supports having a lot of battles everywhere (apologies @credence0x for doubting). Will close this
