### ISSUE TITLE
[CLIENT] [enh] Create wrapper around `getEntityIdFromKeys`

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1149]
For code readability:

Create our own wrapper of `getEntityIdFromKeys` that accepts strings, bigints or number (specifically this last one as we have switched from bigints to number for EntityIds in the client)

**Comment by ShantelPeters** [comment]
@edisontim Can I work this ? This would be my first time contributing to an issue

**Comment by edisontim** [comment]
I think I'll close this for now, it's probably overkill to have this
