### ISSUE TITLE
[CLIENT] Delete army models that are in a battle or dead

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1185]
The query for armies should be 
```tsx
  const armies = useEntityQuery([
    Has(Position),
    Has(Army),
    Has(Health),
    Not(Protectee),
    NotValue(Movable, { sec_per_km: 0 }),
    HasValue(Army, { battle_id: 0 }),
  ]);
  ```
and then we need to filter on armies that have more than `EternumGlobalConfig.resources.resourcePrecision * EternumGlobalConfig.troop.healthPrecision` health

**Comment by od-hunter** [comment]
Hi @edisontim , is this open for contribution? If yes, can I be assigned please?

**Comment by edisontim** [comment]
Gm @od-hunter, sorry we're trying to get this merged quickly so I'll do this myself
