### ISSUE TITLE
[trade routes] Implement first iteration of Trade Routes

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#119]
The first iteration of trade routes. This would create a route between the two Realms.

**Contracts**

**System:**

**create_route**
Inputs - position_x, position_y

**Components:**

**Route**
- entity_id - uuid
- position_x
- position_y

**Usage**
- entity_id - uuid
- number_uses

**Owner**
- entity_id - uuid
- address

**Comment by aymericdelab** [comment]
@credence0x

**Comment by credence0x** [comment]
okay

**Comment by aymericdelab** [comment]
@ponderingdemocritus we were thinking of having to pay to create the route as well, since it does not make sense to just make it free.
