### ISSUE TITLE
[threejs] When changing accounts

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1202]
The labels of your armies and your Realm still show up as if they were an opponent's

**Comment by aymericdelab** [comment]
i think it comes from here:
https://github.com/BibliothecaDAO/eternum/blob/144ce1f421232a922ccbf115707f24fdbb476d89/client/src/three/systems/SystemManager.ts#L107

maybe owner is not updated when changing owner

**Comment by aymericdelab** [comment]
fixed by #1218
