### ISSUE TITLE
[threejs] difference between resource production between entity details and resources panel

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1259]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/2a55359b-35be-4a2b-9989-e4199c175237">

**Comment by cwastche** [comment]
<img width="948" alt="image" src="https://github.com/user-attachments/assets/afeb554c-f442-4362-be5c-ed54c07e1331">

**Comment by cwastche** [comment]
Seems to be an issue in contracts.
Way to reproduce:
1. Build a fishery (Prod. 30/s)
2. Build a farm (Does not update prod. of 1st fishery)
3. Build second fishery (prod 33/s)

**Comment by cwastche** [comment]
Checked out a version before the threejs changes, and this worked before. It seems that the issue is w/ the N-E neighbour hex position. The coordinates of the hexes, in that direction, do not follow a singular algo
