### ISSUE TITLE
[contract] Pillaging should use up the army's stamina

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1276]
Currently, you can pillage an infinite amount of times (or until either army is dead).

1. We should change that to the raiding army using up ALL of its remaining stamina.
2. The amount of stamina you have when raiding should affect the amount of resources you get when successful

Ex: 
if at 100% stam, get 100% of resources
if at 50% stam, get 50% of resources

**Comment by aymericdelab** [comment]
wonder if we should maybe do:
1 stamina point = X amount resource.

Counter argument for % of stamina is that you have units that have different max stamina

**Comment by cwastche** [comment]
Also, should we give different probability rates to each resource when pillaging ? atm all of them are at 1

**Comment by aymericdelab** [comment]
final formula: 
final_troop_amount = current_troop_amount * max_stamina/current_stamina

So you max carriable is a % of your stamina left

**Comment by aymericdelab** [comment]
- when you succeed your pillaging, the resources you pillage depends on the percentage of stamina you have left compared to your max stamina.
- when you pillage, stamina goes to 0 so you need to wait until next tick to pillage again.
