### ISSUE TITLE
[threejs] remove explored hex if tx reverts

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1297]

**Comment by aymericdelab** [comment]
@r0man1337 i've updated the system  in #1299 so that we the onUpdate function knows if the update is an explored hex or an unexplored hex (if tx reverts and optimistic is removed so an explored hex becomes unexplored). 

Could you check how to actually remove the explored hex from the worldmap ?

**Comment by r0man1337** [comment]
Fixed.
