### ISSUE TITLE
[client] Navigating to an enemy Realm 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1304]
If you navigate to an enemy Realm then change back to your Realm, you do not navigate back to your realm but stay on the enemy Realm. This means you have all the actions available, however it is not your Realm

**Reproduce**

1. Navigate to Enemy Realm
2. In top nav change back to your Realm

**Potential Fix**
1. When swapping in the top nav, always take back to Realm selected.

**Comment by edisontim** [comment]
Tried to repro on local + remote but no luck, will leave open for now

**Comment by aymericdelab** [comment]
with #1309 if you're on enemy realm you can't select another realm on top nav, you need to go back to worldmap for that

**Comment by edisontim** [comment]
Indeed, closing this
