### ISSUE TITLE
Incomplete Menu on small screens

### ISSUE THREAD

**Issue by credence0x** [BibliothecaDAO/eternum#133]
**Describe the bug**
Some menu's don't show completely when using small screens

**To Reproduce**
1. Reduce browser window
2. Got to site and settle realm
3. Click market
4. Click `create new offer`
5. The menu won't appear fully

**Expected behavior**
The menu should show completely irrespective of window size

**Screenshots**
https://cdn.discordapp.com/attachments/989804511868620800/1149665801851371571/Screenshot_2023-09-08_at_12.18.14.png

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser chrome

**Comment by r0man1337** [comment]
fixed in #142
