### ISSUE TITLE
[client] Cannot attack enemy army in ended battle

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1330]
ways to reproduce:

1. Battle between Realms A and B.
2. Realm A wins
3. Realm B leaves battle (Realm A army still in battle)
4. Try to attack Realm A army with Realm C: 'Battle' button is greyed out.

**Comment by edisontim** [comment]
Couldn't reproduce but will leave open in case this happens again in the near future

**Comment by edisontim** [comment]
Tried to reproduce a few times and couldn't, will close this
