### ISSUE TITLE
[Client] Market AMM UI issues

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1343]
Addendum: Top element is always Lords. 
Component should be changed accordingly

1. resource icon not centered correctly on 100% viewport
![image](https://github.com/user-attachments/assets/aafa3b71-f662-44c1-a412-8190f8bcbf96)

2. Can only select one resource for both top and bottom element
![image](https://github.com/user-attachments/assets/1b02c200-3849-4347-861f-0b4b66a01fea)

3. Max value displayed on wrong side (Or right side, but should be selected in the top row then) 
<img width="461" alt="image" src="https://github.com/user-attachments/assets/9f527ee5-7eab-4196-8f9d-3b5a3cb46583">

4. Deleting a number gives 'Nan' instead of '0', and is a pain to turn into a number again
<img width="401" alt="image" src="https://github.com/user-attachments/assets/b6ecf355-a740-40e9-9c41-e100e6d5a0d1">

**Comment by aymericdelab** [comment]
fixed by #1400
