### ISSUE TITLE
[client] coord not the same on building new troops for defence army

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1362]
<img width="1730" alt="Screenshot 2024-08-20 at 16 39 28" src="https://github.com/user-attachments/assets/5fd7f6b1-355f-4514-91e8-d8173a7d557f">

**Comment by edisontim** [comment]
Can't reproduce this

**Comment by edisontim** [comment]
This is most likely happening after deleting the defensive army, I had the same issue today, it's going to be fixed by #1406
