### ISSUE TITLE
Quest UX tweak

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1443]
The back button in the quest pop-up is vital for progression, but it is hidden away.  Users need to be guided to it or get stuck.  Suggest highlighting the back button/ Suggest having forward / back arrow for the quest box.

<img width="551" alt="image" src="https://github.com/user-attachments/assets/57641fcd-c762-411f-aed6-c66612de621f">

**Comment by LordSecretive** [comment]
Suggestion - change 'claim reward' button to 'Claim reward and go back to active quests'

**Comment by cwastche** [comment]
Adding on:
Introduce through quests the different mouse click mechanics
