### ISSUE TITLE
Unable to scroll around Realm hex page 

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1448]
no way to move the view to see the bottom hexes

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/40f97e47-83af-4a5c-b0e0-8185d8db5660">

**Comment by ponderingdemocritus** [comment]
@r0man1337 fix here is just to enable 90 degrees rotation only

**Comment by r0man1337** [comment]
Which hexes? All interactve hexes are visible 
![image](https://github.com/user-attachments/assets/2f3258ae-bbb9-499d-be15-d09737bcf69f)

Only these hexes are intended to be observable
