### ISSUE TITLE
UX clarification - army recruitment window

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1450]
When recruiting for an army it says 'Buy Troops' - but I *think* I am drawing troops from my reserve garrison, not buying troops off market.

Suggest change from 'buy troops' to 'Assign troops from garrison' 

<img width="521" alt="image" src="https://github.com/user-attachments/assets/1fefdee4-c802-47d0-b113-066592747691">

**Comment by edisontim** [comment]
That's correct, you're only putting some of your resources troops into your army

**Comment by edisontim** [comment]
Will change the naming
