### ISSUE TITLE
Army capacity info - inconsistencies in symbol and colour of message

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1452]
I have 4 armies and each has a different colour warning about capacity, and some have a warning '!" symbol and some do not.  Should they all be consistent?  Can we add a tool tip to explain what is meant by this info?

Another UX point- the yellow bar (empty in screenshot) represents stamina, but sits directly above 'XX/XX capacity' - making it seem like there is a link between the 2 things when there is not.  

Solution: Separate 'stamina' and 'capacity' data items, and add tool tips to explain them

<img width="521" alt="image" src="https://github.com/user-attachments/assets/83f40699-8e5b-4e50-b71a-ea03d1f0884b">

**Comment by ShantelPeters** [comment]
Hi @LordSecretive i will like to jump on this
