### ISSUE TITLE
I have 3 attacking armies - but only 2 can be seen / clicked on the world map

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1453]
Difficult / impossible to see & click third army

<img width="979" alt="image" src="https://github.com/user-attachments/assets/5bb59143-9bf5-49c7-b864-d264b03b2400">

**Comment by edisontim** [comment]
GM secretive, thanks for raising all these issues! 
Is this an issue where it's hard to right click on the map to move one of the armies or to select one of them from the panel on the left?

**Comment by LordSecretive** [comment]
G’day. Congrats on the hack win. You guys did fantastically and I love seeing you thrive. Issue: hard to click armies on map. I will try again and document on new version. Question: does an army need a certain amount of units to be able to travel? I made some 1 x unit armies that I couldn’t click. On 31 Aug 2024, at 10:05, tedison ***@***.***> wrote:﻿
GM secretive, thanks for raising all these issues!
Is this an issue where it's hard to right click on the map to move one of the armies or to select one of them from the panel on the left?

**Comment by edisontim** [comment]
> G’day. Congrats on the hack win. You guys did fantastically and I love seeing you thrive. Issue: hard to click armies on map. I will try again and document on new version. Question: does an army need a certain amount of units to be able to travel? I made some 1 x unit armies that I couldn’t click. On 31 Aug 2024, at 10:05, tedison ***@***.***> wrote:﻿ GM secretive, thanks for raising all these issues! Is this an issue where it's hard to right click on the map to move one of the armies or to select one of them from the panel on the left? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Thanks a bunch man, we really enjoyed the project so I guess it reflected :) 
Alright, we already have an idea of how to make it easier, what do you think of having armies grouped as one model and there's a popup to choose the army you want to move when clicked?

**Comment by LordSecretive** [comment]
That’s a good idea. The number of armies located at that site is critical information for other player. The way the aggregate unit is displayed is for consideration. Ideally other players will intuit that the hex is current hosting multiple armies at a glance On 3 Sep 2024, at 03:12, tedison ***@***.***> wrote:﻿

G’day. Congrats on the hack win. You guys did fantastically and I love seeing you thrive. Issue: hard to click armies on map. I will try again and document on new version. Question: does an army need a certain amount of units to be able to travel? I made some 1 x unit armies that I couldn’t click. On 31 Aug 2024, at 10:05, tedison @.> wrote:﻿ GM secretive, thanks for raising all these issues! Is this an issue where it's hard to right click on the map to move one of the armies or to select one of them from the panel on the left? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

Thanks a bunch man, we really enjoyed the project so I guess it reflected :)
Alright, we already have an idea of how to make it easier, what do you think of having armies grouped as one model and there's a popup to choose the army you want to move when clicked?
