### ISSUE TITLE
Resource production - quests

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1454]
Can we add more granular quests to walk players step by step through resource production?

Current experience: construct a resource building, and your resources starting to spend automatically, but the player doesn't realise.  

Suggested experience: add a 'switching resource production on and off' quest.  e.g. When you construct a resource building your workers draw upon the resources in your treasury to produce the resources your Realm can generate.  You can pause production at any time by doing X and Y.    Turn production on and off to complete this quest.

**Comment by ShantelPeters** [comment]
Please I’ll like to work on this
