### ISSUE TITLE
Open issues show indicate self

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#146]
<img width="438" alt="Screenshot 2023-09-18 at 08 59 27" src="https://github.com/BibliothecaDAO/eternum/assets/90423308/548776a8-cf85-4392-93d0-884d32f33bb0">

If an open issue is owned by the wallet, then it should indicate this

**Comment by aymericdelab** [comment]
If I understand correctly, you want to be able to see which open orders belong to other realms that you own ? if so , i can fix this
