### ISSUE TITLE
[contract] Capacity not enough when pillaging

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1472]
<img width="617" alt="image" src="https://github.com/user-attachments/assets/a71b96a7-adff-4f46-82ce-bae02ef388e4">

**Comment by aymericdelab** [comment]
happens if your capacity is already full before pillaging, should add a check in the client with tooltip indicating not enough cap

**Comment by cwastche** [comment]
<img width="628" alt="image" src="https://github.com/user-attachments/assets/8c6a5f55-8f62-41be-a64e-89e381ace659">
