### ISSUE TITLE
[DISCORD-BOT] Automatically add user in database when a realm spawns

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1487]

**Comment by edisontim** [comment]
Subscribe to realm created event, get the owner from the event and add in the rust database

**Comment by aymericdelab** [comment]
would be nice to have the option when running the bot.
set this as high as it would be good to have rn as people don't really add their addresses to the bot

**Comment by edisontim** [comment]
This isn't possible actually as we need discord ID when a realm spawns which isn't possible. 

Decided solution is to simply fire a message on realm spawn in the general discord channel, as well as a battle start and still have users manually register. Then if a user is present in the database when send him a message
