### ISSUE TITLE
[Client] Wrong values when accepting trade order after partial buy

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1501]
Was 50k coal for 7.5k Lords.
Bought 10k Coal.
When trying to buy again:

![image](https://github.com/user-attachments/assets/c4744388-9f3c-4064-a37c-4e9bcf6986c5)

**Comment by aymericdelab** [comment]
is this fixed @cwastche?

**Comment by cwastche** [comment]
This has been fixed.
