### ISSUE TITLE
[contract] can't pause production

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1517]
'u128_sub Overflow')

happening on both of my resource productions. 

<img width="583" alt="image" src="https://github.com/user-attachments/assets/7b0ea238-f204-4399-85ab-ef304756bab4">
<img width="899" alt="image" src="https://github.com/user-attachments/assets/c13c2947-0000-47a7-ae9b-587afc8ca52c">

**Comment by aymericdelab** [comment]
@credence0x would you know where it comes from ?

**Comment by credence0x** [comment]
this issue is killing me

**Comment by aymericdelab** [comment]
<img width="945" alt="image" src="https://github.com/user-attachments/assets/eb724cbf-2db3-4c17-8a2e-6cfc615b3720">

**Comment by aymericdelab** [comment]
<img width="357" alt="image" src="https://github.com/user-attachments/assets/3fef6a82-e606-4ad8-ba74-46a2d4724754">

<img width="343" alt="image" src="https://github.com/user-attachments/assets/0d728bbb-125e-422a-a80f-241318f9594a">
