### ISSUE TITLE
[client] Production issue

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1522]
![Screenshot 2024-09-08 at 15 08 41](https://github.com/user-attachments/assets/a9b95036-da27-4fef-80ee-c055ddba40a8)

Reproduce.

1. Build two production buildings that depend on each other
2. In this scenario, copper should be consumed (i think it is, but client not reflecting)

**Comment by ShantelPeters** [comment]
Hi @ponderingdemocritus can I work on this

**Comment by edisontim** [comment]
Couldn't reproduce this on my side but will leave open for now in case it pops up again

**Comment by cwastche** [comment]
I think #1682 might have fixed this issue
