### ISSUE TITLE
realms stuck after random actions like moving an army or opening the market

### ISSUE THREAD

**Issue by caillef** [BibliothecaDAO/eternum#1529]
The music stops and the UI is removed after these steps:

1. Start a fresh game
2. Make all the quest until the army ones
3. Create an army with 100 swordsman
4. Open the World view
5. Move the army on the left cell next to the Realms
6. Move back the army in the realms

At that point, the UI was gone, music stopped, and I got these errors
I then opened my Realms (screenshot under), but the error was happening in the world view.

<img width="685" alt="Screenshot 2024-09-09 at 10 43 54" src="https://github.com/user-attachments/assets/5d2916e5-b576-4d34-b861-d21b4090fb78">

- OS: mac
- Browser: brave
- Version: [Version 1.69.160 Chromium: 128.0.6613.114 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by caillef** [comment]
on refresh of the webpage, same error:

<img width="408" alt="image" src="https://github.com/user-attachments/assets/9e40813e-2995-4769-9e7f-09bf5a06534f">

**Comment by caillef** [comment]
I started a new realms as this one was broken, but got the error again a bit later, after clicking on the market
<img width="408" alt="image" src="https://github.com/user-attachments/assets/ecbb6b98-1f75-4f79-a84f-f2591d1ab257">

**Comment by edisontim** [comment]
Has this been fixed @cwastche @aymericdelab ?

**Comment by cwastche** [comment]
Fixed by #1535
