### ISSUE TITLE
[client] Battle buttons diff between view & entity military panel

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1536]
From battle view, buttons are disabled:
<img width="527" alt="Screenshot 2024-09-09 at 14 27 54" src="https://github.com/user-attachments/assets/968514a5-86c7-4068-ab66-aa23fc1f6baa">
![image](https://github.com/user-attachments/assets/51f3c4aa-ef70-464b-adea-77be39a56df2)

From Entities tab:
<img width="595" alt="Screenshot 2024-09-09 at 14 28 13" src="https://github.com/user-attachments/assets/4fda22d5-a33f-45be-aa80-ca8d47fd18bc">
<img width="1025" alt="Screenshot 2024-09-09 at 14 28 21" src="https://github.com/user-attachments/assets/08b8641c-f0c7-47f4-b60f-e868e305718f">

**Comment by edisontim** [comment]
This is normal, one must need to be able to check out a finished battle, either to remove his troops from there of just to see the battle state or history. Once the battle is done like in your screenshots, you can attack any of the armies left in the battle so you need to have different buttons for both viewing and attacking

**Comment by edisontim** [comment]
Can I close this @cwastche ?
