### ISSUE TITLE
[contract] don't lock resources on attacked realms

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1559]
cons of locking resources:
- people can stop you from trading with small armies (and you need to leave battle with your realm after battle is over everytime).
- you are helpless once a big army comes and sieges you.

pros of locking resources:
- the sieged realm can just send out all their resources outside of the realm

i think people should be allowed to remove their resources outside of their realm during combat  **Their realm will be conquered anyway so that's already a big loss.**
If the attacker wants to make sure he gets some resources he can **pillage**.

**Comment by ShantelPeters** [comment]
@aymericdelab  I will like to take this up please
