### ISSUE TITLE
[client] add navigation controls

### ISSUE THREAD

**Issue by r0man1337** [BibliothecaDAO/eternum#1561]
Navigation system was implemented recently
![image](https://github.com/user-attachments/assets/b87fa76d-1d76-4e8e-b4b2-16c93883607c)
![image](https://github.com/user-attachments/assets/07b90f1a-e72b-4c17-a347-a881db39f3f0)

Need to add utility buttons for it to game UI (e.g. Navigate to Structure)

**Comment by aymericdelab** [comment]
add compass logo as well to pin entities like armies, realms, your own realm

**Comment by r0man1337** [comment]
Added navigation buttons to armies list.
