### ISSUE TITLE
[client] Small hyperstructures UI fixes

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#158]
- [x] when you don't have any realm settled, you don't see hyperstructures list. But it should be visible.

- [x] verify the location of the hyperstructures on the map, do they each correspond to the closest one to their order.

- [x] when you click on "show on map", it shows a black screen.

- [x] my order tab in hyperstructures does not have anything inside

**Comment by r0man1337** [comment]
fixed in #199
