### ISSUE TITLE
[client] Add notifications related to hyperstructures

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#159]
- [x] When your caravan has arrived to the hyperstructure
- [ ] When someone has given your hyperstructure some resources

**Comment by ponderingdemocritus** [comment]
has this been actioned?

**Comment by aymericdelab** [comment]
not yet

**Comment by ponderingdemocritus** [comment]
This looks complete - am i correct?

**Comment by aymericdelab** [comment]
we can close combat notifications, but haven't had time to do hyperstructures so let's leave it open for now
