### ISSUE TITLE
Pause production doesn't update rates of consumption in right hand panel

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1640]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/483cae87-8595-4c07-8e0f-1b66a424e3be">
 paused but still showing flow of resources out of my inventory on right hand side, and quest not marking as complete to claim rewards

**Comment by LordSecretive** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/984aaed7-8195-4587-9fa0-591cf75884ce">

**Comment by aymericdelab** [comment]
fixed by #1662
