### ISSUE TITLE
DMs in chat - make threads with individual, don't mix in with global

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1643]
not possible to discern easily which of my messages are public vs global (all my messages same colour)

<img width="404" alt="image" src="https://github.com/user-attachments/assets/52eba1e4-b66b-4765-800e-358cb9ce3cf2">

**Comment by aymericdelab** [comment]
@edisontim when clicking on loaf here, you should only see the messages between the 2 of you
