### ISSUE TITLE
Spy / ranger units to give something to do on world map when stamina is so limited

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1647]
could we add a 'spy' or ranger unit that can explore hexes but not collect resources.  They could move 3x or 5x times as far, for scouting, but then the info about what was on the hex would be public, leading to a race to claim good discoveries.

that would help me to satisfy my itch to click around and explore the map when out ofarm stamina

**Comment by ponderingdemocritus** [comment]
closing - will be adjusting current characters
