### ISSUE TITLE
Land I have already explored - the map shows the fog of war

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1653]
where i see the illustration of a mountain, I should see a biome for a previously explored hex?

<img width="427" alt="image" src="https://github.com/user-attachments/assets/1b0bdf38-f87b-4db2-adf6-755df2b47c02">

**Comment by LordSecretive** [comment]
resolved on refresh

**Comment by aymericdelab** [comment]
@r0man1337 some chunk issues still
