### ISSUE TITLE
Mismatch of production rate

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1654]
Left hand panel says 10 p/s, right hand panel shows 10 p/s

had this for both my resources structures (hartwood and cold iron)

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/7c002df4-542e-474d-b0e0-c41402342d9e">

**Comment by od-hunter** [comment]
Hi @LordSecretive , can I be assigned this please?
