### ISSUE TITLE
[client] easily search for specific resource price in the amm

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1656]
<img width="1307" alt="image" src="https://github.com/user-attachments/assets/eb12ccff-188d-4754-a6aa-9478e09cd4c2">

**Comment by edisontim** [comment]
think this is already done @aymericdelab ? @cwastche also added a search functionality for the resource that you want to trade in the AMM

**Comment by cwastche** [comment]
Fixed by #1696
