### ISSUE TITLE
[client] sell and buy on the left are inverted ? 

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1657]
when you click on stone you expect to be able to buy some for 0.01, but it's actually the lowest price at which you can sell. Seems like these are inverted

<img width="1292" alt="image" src="https://github.com/user-attachments/assets/92289831-0f14-4b32-a4ee-2582c817cc53">

**Comment by cwastche** [comment]
Fixed by #1696
