### ISSUE TITLE
[Contracts?] Max resource not limited by storehouse limit ?

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#1668]
Bal sold 100% of its fish on the AMM (10M)
15mins later, could sell more than he should've produced

Update: We think the issue stems from the following:
When a resource is updated via AMM trade, transfer, etc... we first 'burn', and then 'save/harvest', making the production ticks that happened while you were at max capacity still produce resources for you.

![image](https://github.com/user-attachments/assets/57208eb1-a7b4-405d-9e7d-16deb971f627)
![image](https://github.com/user-attachments/assets/dff1eb6c-5f65-41f3-be57-41738dbfe821)

**Comment by od-hunter** [comment]
Hi, can I work on this please? @cwastche
