### ISSUE TITLE
[Client] - Tick to update ressources and time left is not consistent

### ISSUE THREAD

**Issue by bal7hazar** [BibliothecaDAO/eternum#1669]
![image](https://github.com/user-attachments/assets/08a9eda4-7eae-4273-a5e2-da55dff4500e)

The ressource quantity is updated every second where the remaining time is updated every 10 seconds (block time).

It can be fix to be consistent between the 2 information.

Also, when the resource reaches 0, it optimistically keep decreasing until a new block time is set (every 10 seconds), add a simple condition to check display a positive quantity or zero could fix it.

**Comment by aymericdelab** [comment]
i think this is because the left one is using date.time() and the right one is using nextblocktimestamp (every 10 sec)

**Comment by edisontim** [comment]
Closing as we're only displaying days, hours, minutes now
