### ISSUE TITLE
UX discussion: flip buy and sell table headers?

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1685]
UX discussion: Iook at Obsidian (highlighted).  The column titles in the table  'Sell'  and 'Buy' seem flipped, to me
Image

I can buy at 1.90 and sell at 0.01, but if i look at the table on the left the column headers say the opposite.

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/06e972e2-d23d-4d5b-b6d7-b271efc3cd7f">

**Comment by edisontim** [comment]
I think this has already been fixed @aymericdelab ?

**Comment by aymericdelab** [comment]
Yes fixed
