### ISSUE TITLE
Can this box in the UI show max capacity and current store?

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1699]
Currently tells me maximum, but not current storage e.g. 7,555 of 10,000

<img width="129" alt="image" src="https://github.com/user-attachments/assets/78925c2b-fb15-4f8a-a2ba-e6b81d17d041">

**Comment by cwastche** [comment]
This is more of a UI clarity issue, as this indicates the storage capacity for each resource individually, not summed up

**Comment by ponderingdemocritus** [comment]
closing as redoing in new UI
