### ISSUE TITLE
[contracts] Should battle time be recomputed every time someone joins?

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1711]
Right now, if you have an army that's smaller than the other one, the bigger one loses more troops /s than the smaller one.

The issue with this is that if a tiny army joins the battle, battle is now in a different state that the beginning (i.e. it has lost more troops, so it will be more balanced than at the beginning), so the time will be squewed and it will be more and more favorable towards the small army

**Comment by ponderingdemocritus** [comment]
yes - we need to make battles last longer than 8hrs if more join. Battle should rage for days and days.

**Comment by edisontim** [comment]
this will be closed by #1741

**Comment by edisontim** [comment]
this is closed
