### ISSUE TITLE
[contracts + config] Increase Costs per building type

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#1720]
Each building costs more than the last

**eg:**
Farm 1 = 100 Wheat
Farm 2 = 150 Wheat
Farm 3 = 200 Wheat

Keep buiulding counter * scale figure = fixed resource cost for the next building

**TODO:**
- [ ] Config 
- [ ] Building counter
- [x] Client work to adjust config so reflects around the app

**Comment by cwastche** [comment]
Finished by #1727
