### ISSUE TITLE
[contract] make bank claimable + add bandits

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1787]
1. need to change this to ```tile.explored_at```
https://github.com/BibliothecaDAO/eternum/blob/2dca26a23eb6f2f9dae3c7ccc4378d6f92a601e9/contracts/src/systems/transport/contracts/travel_systems.cairo#L127-L128

2. add mercenaries on admin bank (same amount as fragment mine for example)

**Comment by edisontim** [comment]
Closed by #1792
