### ISSUE TITLE
[client] Add scroll bar to the list of your own caravan

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/eternum#181]
As seen in the below screen recording, while sending my resources to the hyperstructure, I had 6 available caravans but I couldn't access the ones at the bottom of the list (or have access to 'send caravan' after selecting one from the top) because I couldn't scroll.

https://github.com/BibliothecaDAO/eternum/assets/91049656/2eee6ec2-4f97-441d-88f2-df86bd4bcc74

**Comment by r0man1337** [comment]
Fixed in #199
