### ISSUE TITLE
Move & Explore improvement

### ISSUE THREAD

**Issue by Sir-Markalot** [BibliothecaDAO/eternum#1817]
Observation:
Moving and exploring around the map is a little confusing especially for new users, feels like its missing a step to make it more intuitive. 

Issue:
Moving an army by mistake

My experience:
Numerous times I have gone to click on a realm or mine to view it, but have accidentally moved an army towards it. 

How can this happen:
- Typically i'm moving an army, then forget to [ESC] before clicking a nearby structure to view. 
- I go to click on another army to select ready for a move, but again haven't [ESC] from the last army move, and end up moving the previous onto the Hex of the one I wanted to select. 
- switching to world view, an army is automatically selected to move

Suggestions:
- a mode toggle between MOVE/EXPORE? 
- add a "CONFIRM MOVE" step into the mechanics?

**Comment by aymericdelab** [comment]
linked to #1859
