### ISSUE TITLE
Infinite production of Alchemical Silver

### ISSUE THREAD

**Issue by robertkodra** [BibliothecaDAO/eternum#1819]
I’ve built an Alchemical Silver production, but I have zero resources of Twilight Quartz and Adamantine, yet it’s still producing. This seems to be a backend bug, not a front-end issue, as I’ve already listed all my produced Alchemical Silver on the market.

![image](https://github.com/user-attachments/assets/be42dda5-9899-488e-a37f-b7c57bbf2251)

**Comment by ponderingdemocritus** [comment]
this is issue with client

**Comment by edisontim** [comment]
![image](https://github.com/user-attachments/assets/e46c4479-a4e5-4fca-aac4-dbe0d2d89d36)
Secretive got this with copper as well, looking into it
