### ISSUE TITLE
[client] add move bounds for popups

### ISSUE THREAD

**Issue by r0man1337** [BibliothecaDAO/eternum#1887]
make it impossible to move popups beyond the visible borders of the screen, add an auto reset if the popup somehow ended up there

![image](https://github.com/user-attachments/assets/26032cb9-afdc-435b-8801-36b32b5fc060)

**Comment by aymericdelab** [comment]
can you take a look @r0man1337 ?

**Comment by r0man1337** [comment]
Fixed in #1964
