### ISSUE TITLE
[client] event stream of actions done by other players to you

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#1908]
things like :
- someone attacked you 
- someone pillaged you
- someone joined a battle in which you are
- someone accepted an order from you

which are usually events that are linked to you or one of your entities by other players

would be useful when people log in everytime and they can have a quick look at what happened

**Comment by aymericdelab** [comment]
maybe a different tab in the event stream window

**Comment by ponderingdemocritus** [comment]
good idea - this should popup once a user returns from being away
