### ISSUE TITLE
Change Guild to Tribe

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1941]
For this round, suggest we change the word 'guild' for 'tribe' in the UI and docs please.  We want it to be very welcoming for 2+ players to set-up tribes and not feel the game is for mega guilds

<img width="605" alt="image" src="https://github.com/user-attachments/assets/65b429cf-cfbf-4e59-858b-c862416ce2f3">

**Comment by aymericdelab** [comment]
already tackled by issue #1934
