### ISSUE TITLE
Cartridge wallet address copy function

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#1952]
To make it easy to add players to tribes can we make it very easy to find and copy your cartridge wallet from the game sceeenn

Floppy Flop had a 'copy wallet address' button in top right corner of screen

**Comment by bob0005** [comment]
This already exists within the 'Settings' panel

<img width="401" alt="image" src="https://github.com/user-attachments/assets/c6600438-6126-4134-bdf9-e747c77b7aeb">
