### ISSUE TITLE
[contracts] be able to level up by spending resources bit by bit

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#2036]
if you need to hold the whole balance at once, you need a huge amount of storehouses to hold the resource balance

![image](https://github.com/user-attachments/assets/885a7f46-57d4-4197-bbff-ff285bf55efa)

**Comment by aymericdelab** [comment]
not necessarily bug, but seems like storehouse need is way bigger than anticipated

**Comment by ponderingdemocritus** [comment]
perhaps we need to make resources weigh half as much
