### ISSUE TITLE
[client] Multiple battles bug

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#2086]
![image](https://github.com/user-attachments/assets/8f796e06-b8db-4d2e-bc36-a5080fc7cb0e)

A battle is currently happening on the same hex as the hyperstructure but I cannot attack the hyperstructure or realm separately because it is on the same hex. It only allows me to add to the pre-existing battle even though I have a separate army that should be able to simultaneously attack the HS army and/or realm army.

**Comment by edisontim** [comment]
Didn't manage to reproduce this, I can go in the entities tab and simply attack the other army. 
Granted the UI isn't great, it probably makes more sense to have entities and battles in the same tab and have filters. I'll change that
