### ISSUE TITLE
[playerhouse] update controller on ph client 

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#2121]
![image](https://github.com/user-attachments/assets/32928a44-ea3a-45de-8def-0d73e3f58013)

**Comment by aymericdelab** [comment]
dropped a msg in catridge discord to know what's going on

**Comment by edisontim** [comment]
Do we really need this? I thought we could just spectate?

**Comment by aymericdelab** [comment]
We need to login first before spectator

**Comment by aymericdelab** [comment]
yeah we should add spectator before login but it wasn't straightforward, so
i was trying to see if we could just get the controller to work first

**Comment by edisontim** [comment]
Player house is done anyways, I think the torii and katana instances have been shutdown by Cartridge. I'll work on spectator mode without having to connect
