### ISSUE TITLE
[client] fragment mines resources

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#2230]
some weird stuff going on. Fragment mines should just have fragments on them.

![image](https://github.com/user-attachments/assets/3d0042b7-8261-4c6d-bd3e-57e7433e30e9)
![image](https://github.com/user-attachments/assets/6d710a8d-938e-4226-a1ca-8ca2b4973bdb)

**Comment by ponderingdemocritus** [comment]
did someone deposit?
