### ISSUE TITLE
feat: 2 new pages in onboarding flow with 'tick to agree'

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/eternum#2233]
### Describe the feature you'd like to request

ONBOARDING ADDITION 1

**Important Disclaimer – Please Read Carefully**

By playing **Eternum**, you acknowledge and accept that:

- **Immutable Contracts:** The game operates entirely on immutable smart contracts. Once deployed, these contracts cannot be altered or modified by the developers or any other party.

- **Risk of Loss:** All transactions and gameplay actions are final. There is no mechanism for refunds, reversals, or compensation.

- **Acceptance of Risk:** You are solely responsible for any loss of funds incurred while playing Eternum. By playing proceeding, you waive any claims of recourse against the developers, the DAO, or associated parties.

**Acknowledgment Required:** To participate in Eternum, you must acknowledge and accept these terms by ticking the box below.
---------------------

ONBOARDING ADDITION 2

**Funds Locked at Season End – Please Read**

A season of **Eternum** concludes when a single player scores the required [number] Victory Points and clicks the "End Season" button.

- At the moment the "End Season" button is clicked, **ALL $LORDS tokens and in-game resources are permanently locked in the game.**
- Please review the [game documentation](https://eternum-docs.realms.world/) for full details, including instructions on bridging tokens out during the gameplay phase.

**Acceptance of Risk**: By participating in Eternum, you agree to the risk of loss of funds with no recourse and accept all terms detailed in the [documentation](https://eternum-docs.realms.world/).

**Acknowledgment Required**: To proceed, you must tick the box below to confirm your understanding and acceptance of these terms.

Style ref:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/941ff83f-bd50-4700-aaa6-a64d82ed25e9">

### Describe the solution you'd like to see

.

**Comment by ponderingdemocritus** [comment]
@edisontim can you include a tick box in the client

**Comment by edisontim** [comment]
> @edisontim can you include a tick box in the client

i feel like the fact that we say that if they continue they accept the terms is enough no?

**Comment by LordSecretive** [comment]
This is a general onboarding thing not a cartridge thing

This copy supplied was intended to be 2 separate stages.  We want people to know that 48 hours after the game ends funds are all locked in to the contract forever.  Now that critical info is lost.

Here is a proposed copy edit - please treat as priority before people bridge into game

https://docs.google.com/document/d/1ZPi3hal4uMm6H0UdSABGOhj5xSojnxInIGn8XqLnN9k/edit?tab=t.0

**Comment by LordSecretive** [comment]
Take a look at screenshot - no-one is reading that, but THEY MUST KNOW THAT THE GAMES BRIDGES CLOSE 

it can't get lost in Terms of Service - i can't stress this enough

This copy supplied earlier this week was intended to be 2 separate stages. We want people to know that 48 hours after the game ends funds are all locked in to the contract forever. Now that critical info is lost in a wall of merged text.

Here is a proposed copy edit - please treat as priority before people start to bridge into game

https://docs.google.com/document/d/1ZPi3hal4uMm6H0UdSABGOhj5xSojnxInIGn8XqLnN9k/edit?tab=t.0


<img width="650" alt="image" src="https://github.com/user-attachments/assets/7d5d94db-2a2f-41c0-92b8-d303b2513d8c">

**Comment by LordSecretive** [comment]
Terms of service link not clicking

<img width="478" alt="image" src="https://github.com/user-attachments/assets/f9cceea6-8dd1-4525-a97e-6dce51ed5744">

**Comment by ponderingdemocritus** [comment]
made screen bigger, tow pages and is clickable
