### ISSUE TITLE
Don't show resources that are already shown in main screen

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#244]
When you click on show all resources. Don't show the ones that are already shown on the left because they are either food or they are on your realm.

![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/b5d7ce6a-a04b-4543-8e5d-8de5a612d909)

**Comment by idrak888** [comment]
Hi I am interested in working on this

**Comment by aymericdelab** [comment]
Ok good !
