### ISSUE TITLE
[contract + client] Assign a username to each address

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#245]
We'd like to assign a username to each address, so that it's easier to know that certain realms belong to one player.

To do that we could add a "Username" field to the Signup component when loading the app.

Setting a username should only be done once per address and should trigger a tx which should assing
``` 
Name { 
#[key]
address: ContractAddress
value: string 
}.
```
to each address.

Once you have set your address username, you should not be able to change it.

![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/9f7f7845-c578-4559-bc99-cd282eeb316b)

**Comment by ponderingdemocritus** [comment]
perfect
