### ISSUE TITLE
Creating a 'Capital' Realm within your wallet

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/eternum#250]
New feature idea that allows you to assign one of your Realms as the Capital.

Current use-case would be making it easier to send resources to one Realm to initiate the hyperstructure - maybe there is a 'send to capital' button, an icon next to the Realm when searching through them, or simply a capital filter. 

This could also create new features/gameplay around Capitals, eg bonuses when raiding a capital, decreased happiness across all Realms in a wallet when a Capital is raided, or when you trade with a Capital you can't attack any Realms within their wallet for 7 days etc etc.

**Comment by ponderingdemocritus** [comment]
I like the idea, but needs some thought around it.
