### ISSUE TITLE
Allow single-sided trading between your own Realms within a wallet

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/eternum#251]
Currently you can't send resources within your empire without sending resources to the other, which wastes the use of donkeys.

Requesting the feature to allow sending resources from Realm A to Realm B (within the same wallet) without B sending anything to A.

**Comment by ponderingdemocritus** [comment]
@credence0x is this possible contract wise ?

**Comment by credence0x** [comment]
> @credence0x is this possible contract wise ?

yeah its possible to do that rn. We just need a UI update.

What would happen is that `Realm A` would approve `Realm B `to spend x amount of resources. Then `Realm B` would create a caravan with enough capacity to carry the resources and send it to Realm A. Then the caravan picks up the resources that `Realm B` is approved to spend (by calling `transfer_from` )then returns back home.

That's how winners are able to pick up resources won in the casino.

**Comment by ponderingdemocritus** [comment]
similar to #252
