### ISSUE TITLE
Bulk sending resources between Realms in the same wallet

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/eternum#252]
Currently its a timely process sending resources to one Realm from your other Realms - eg when initiating a hyperstructure. 

Being able to do this in bulk would improve this flow much better, or at least being able to cycle through them in a table, and then creatin the caravans on a single screen at the end.

**Comment by ponderingdemocritus** [comment]
Yeah we need an 'Advanced' Empire view to make this easy.
