### ISSUE TITLE
Update naming of resource production

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#258]
Wood Mill
--
Stone Quarry
Coal Mine
Copper Mine
Obsidian Quarry
Silver Mine
Ironwood Mill
Cold Iron Mine
Gold Mine
Hartwood Mill
Diamonds Mine
Shappire Mine
Ruby Mine
Deep Crystal Mine
Ignium Mine
Ethereal Silica Mine
True Ice Quarry
Twilight Quartz Mine
Alchemical Silver Mine
Adamantine Mine
Mithral Mine
Dradonhide Deposit

**Comment by gogibear** [comment]
Sapphire*
