### ISSUE TITLE
resources/realm attack window  opens at an off place I can't view or move..

### ISSUE THREAD

**Issue by Freakazoid78tr** [BibliothecaDAO/eternum#265]
I think I attached a picture of it here but it shows as a link. Not sure if I did this right. First time using github.

The tab opens all the way at the corner of the screen and the top of it is not visible for me to pull down to see it fully. 

![scren off](https://github.com/BibliothecaDAO/eternum/assets/102276968/3fc3b512-90a2-4699-a55f-f50c5be0277d)

**Comment by r0man1337** [comment]
Bug is fixed, but who already encountered it must reset browser's localStorage.
