### ISSUE TITLE
Create Offer box view blocking resources and unable to drag

### ISSUE THREAD

**Issue by spaghettiOnToast** [BibliothecaDAO/eternum#267]
If you have moved the "create offer" box too far in a direction that moves it off screen (only partially) it is unable to be dragged/reset back to the original position unless you remove from local@storage. In this example, I could not add certain resources to an offer. 

![Screenshot 2023-11-25 at 00 27 32](https://github.com/BibliothecaDAO/eternum/assets/112407419/0e6ad913-d157-4566-9c43-8987e7c774fd)

**Comment by r0man1337** [comment]
Fixed.
