### ISSUE TITLE
bug: to small icon of the resource in the "my offers" list

### ISSUE THREAD

**Issue by blackmirrordesigner** [BibliothecaDAO/eternum#329]
### Provide environment information

macbook - google chrome

### Describe the bug

To small icons in the "my offers" list. Make them 1.3 rem please:
<img width="1493" alt="image" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/91994843/01f9eff4-891e-432f-9be5-2c2feae85c80">
`<div class=" mx-auto w-2 h-2 md:w-4 md:h-4 mb-1 "><img src="/images/resources/11.png"></div>`
`width: 1.3rem;`

### Link to reproduction

https://next-eternum.realms.world/realm/326/my-offers

### To reproduce

create one order and then open My offers

**Comment by aymericdelab** [comment]
agreed with you, in lots of parts of the app the resource icons are way too small, have increased their size where needed

<img width="466" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/05826a0c-3448-4398-9876-199bc99e59c4">

<img width="455" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/87c07db0-a8ae-46de-a48c-dbb42080b7fd">


<img width="358" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/2a923382-f073-43bb-a7e1-cd6402a5e618">

<img width="366" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/d9db7e5c-9933-44ae-8db6-3b7cf4b4e41b">

<img width="469" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/6b93a893-2840-4f11-b00b-f78f4f82c669">
