### ISSUE TITLE
Direct order receiving issue

### ISSUE THREAD

**Issue by Freakazoid78tr** [BibliothecaDAO/eternum#331]
I created a direct offer from one of my realms to another one with 5-6 resources on it. I had no issues creating it but when I went to receive it, the number of donkeys didn't default, hence I couldn't receive the offer. Even if I entered random number of donkeys in there, nothing happened because the total weight of the order failed to calculate I think. 

I then tried to direct offer reach resource separately, one by one. That worked and I had no issues creating/receiving those orders EXCEPT one resource (ironwood) for which the transfer quantity was below 100 units. Any other resource I transferred was more than 100 units. Not sure if this has anything to do with the issue but wanted to bring it up. 

Below is the screenshot from the receiving realms POV where I can't receive it. Thanks Lords!

![image](https://github.com/BibliothecaDAO/eternum/assets/102276968/c6daa0c2-aec9-4b7d-8bea-ca4a9b0f9364)

**Comment by aymericdelab** [comment]
gm ser, seems like the issue was due to the ironwood weight not being correctly set.

Bug has now been fixed.
