### ISSUE TITLE
Incoming trade didn't appear

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/eternum#336]
I did a trade between two of my Realms, sending a lot of resources to one and sending only 1 fish to the other. Once finishing the trade (and adding roads), only the fish trade appeared on the Realm B's 'My Offers' tab. 

Now the trade is complete and the caravans have arrived, but still only the fish arrived. 

Under the caravan tab you can see both trades though.

<img width="340" alt="Screenshot 2024-01-08 113151" src="https://github.com/BibliothecaDAO/eternum/assets/91049656/efa99f07-9c8b-4a94-9835-708b50a3e3a4">
<img width="362" alt="Screenshot 2024-01-08 113210" src="https://github.com/BibliothecaDAO/eternum/assets/91049656/a716303e-4e39-4f20-86f4-deef4884e03c">
<img width="1474" alt="Screenshot 2024-01-08 113244" src="https://github.com/BibliothecaDAO/eternum/assets/91049656/f39f11f0-8913-41f0-b0bc-b9793d6ad1c1">
<img width="1493" alt="Screenshot 2024-01-08 113257" src="https://github.com/BibliothecaDAO/eternum/assets/91049656/0f87ee25-7615-4208-abd3-cfee098c9d0d">

**Comment by aymericdelab** [comment]
is it still missing ?
