### ISSUE TITLE
Trading filter request

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/eternum#337]
Can we add a filter to bid/asks of resources you have enough assets to accept. Currently you have to scroll through to find offers you can execute.

<img width="423" alt="Screenshot 2024-01-09 at 10 48 08" src="https://github.com/BibliothecaDAO/eternum/assets/114863662/33f7b14d-ebb2-45df-b16d-653640c8db78">

It might be worth sorting all offers you can accept to the top of the trading tab!

**Comment by aymericdelab** [comment]
thank you ser, very good proposal.

I've just added a "Can Accept" checkbox on the top
