### ISSUE TITLE
Clipping issue with the Market Screen

### ISSUE THREAD

**Issue by clicksave** [BibliothecaDAO/eternum#341]
**Describe the bug**
When the marketplace is moved on top of the City dashboard it results in some weird clipping behavior

**To Reproduce**
1. Go to 'City'
2. Click on 'trade tab -> Marketplace'
3. Move the marketplace over the city tab

**Expected behavior**
The city dashboard should be fully behind the marketplace

**Screenshots**
![image](https://github.com/BibliothecaDAO/eternum/assets/3332646/787b9acc-47a0-4f2e-a456-ba55b2940086)
<img width="724" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/3332646/fa5be611-3beb-4284-b4a5-29eec78b72fe">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Mac]
 - OS: [MacOS]
 - Browser [Arc (chrome)]

**Additional context**
pretty self explanatory

**Comment by r0man1337** [comment]
Fixed in upcoming PR
