### ISSUE TITLE
Issue with Search in the Create Offer Menu

### ISSUE THREAD

**Issue by EazyRonin** [BibliothecaDAO/eternum#342]
**Describe the bug**
When you are trying to make a direct offer using the name of a realm.  If the realm has an accent over the letter.  The realm will not appear.  For example it looks like e needs to be mapped with è

![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/bafbafd2-532f-403f-a82f-b398bc39f68e)

**To Reproduce**
1. Go to Create new offer
2. Click on the items you would like to trade
3. Click +Make Direct Offer
4. Type Useles in the search by ID or Name field, or Just "us"
5. The Scroll bars to the right of the menu are not functioning.
6. If you press the down error the menu to the left scrolls down and not the direct offer menu.
7. The realm does not appear at the top of the search.

**Expected behavior**
The issue is that realms with special characters are being affected by searches in the create offer menu.  This issue is being exacerbated by the scroll bar and down arrows not working, as well as by the search bar not taking into account the placement of the letters that you are using to perform a search.

**Screenshots**
Trading Screen issues
Issue 1.   When you are trying to make a direct offer and type in the name of a realm.  If the realm has an accent over the letter.  The realm will not appear.  Looks like e needs to be mapped with è
 
![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/7a7ea555-9877-447b-a86c-7f6a3173ac0b)

It looks like the realms are not appearing in the create offer menu, even when you add the letters with accents.  
 
![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/83d34aad-6af4-4f62-98a6-7f82bdc0fe8a)

Issue 2.
The search bear array in the create offer menu needs to be adjusted.   For example, when searching “us for the Useles realm it’s pulling all reams with “us” in the name.  The search should start with all reams with U first in the case.   It means that the programming logic needs need to be adjusted on the search bars.  I had to have this kind of item fixed for a site that I owned.  It’s not a simple fix, but important to help players find what they are searching for.
 
![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/d90c4b15-74df-4d8f-92a6-72e04ab41b64)

Issue 3.
While in the create offer menu.  If I try to scroll down using the down error. The create offer menu is unresponsive. While the menu to the left starts scrolling down.
Before Example:
 
![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/08206459-d96c-468c-9046-b8f38d902d73)

After Example: 
 
![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/a06f9518-fbcd-4beb-a183-684e48862987)

Issue 4:
The scrolling slider on the create offer menu is not functioning. Even when I increase the size of the menus.  Both sliders on the right of the Create Offer Menu are not functioning.
 
![image](https://github.com/BibliothecaDAO/eternum/assets/90276832/f5680691-5bc6-49cf-ae8e-1c0a006664af)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser  Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by r0man1337** [comment]
1. Fixed
2. Fixed
3. What do you mean? scrolling with "Down" key? afaik scrolling divs with arrows is not supported by default in browsers
4. Can't reproduce. Both scrolls working. Can you check if this issue still relevant?
