### ISSUE TITLE
More info/stats on a realm in the "Travel Raiders" window

### ISSUE THREAD

**Issue by dfenland** [BibliothecaDAO/eternum#345]
When choosing a realm to raid from the 'Travel raiders' window, it would be fun to see more information to help with the decision - for example, resources they are able to produce, battle history ie how aggressive/victorious they are, how wealthy they are etc.

![showresources](https://github.com/BibliothecaDAO/eternum/assets/156480685/ecbdefd9-3e5a-4554-9cc8-290fda3ddebe)

**Comment by ponderingdemocritus** [comment]
This is changing, so closing
