### ISSUE TITLE
Allow for raiders to explore more than once before offloading resources

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#375]
**Is your feature request related to a problem? Please describe.**
Currently the raiders can only explore once, and need to offload their discovered resources in their realm, before being able to explore again.

**Describe the solution you'd like**
In the contracts, they should be able to carry more resources. Each resource being on a new spot in their inventory.
In the client, you need to change this line:
https://github.com/BibliothecaDAO/eternum/blob/4c097a4c944a128b267e5fbb01f613d0dd0e3fe8/client/src/components/worldmap/ChooseActionPopup.tsx#L96

**Comment by credence0x** [comment]
resolved by #392
