### ISSUE TITLE
See enemy armies in the client

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#376]
**Is your feature request related to a problem? Please describe.**
Currently we only see our own armies on the map. 

**Describe the solution you'd like**
Let's add a new EnemyArmies component that fetches all the enemy armies and displays them on the map. They should have a different color from your own armies. And should not trigger anything when clicked on it.

**Comment by credence0x** [comment]
@aymericdelab don't you think we'll have performance issues if we show all enemy raiders?
