### ISSUE TITLE
Disable (gray out) actions that the player cannot take

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#39]
We need to do a better job at communicating to the player what options they have, what options they don't have and what they need to do to get those options.

For example. right now, a player can click "Accept" on an offer that they do not have the resources to execute. This leads them down to a dead end in the UI. Better to grey out the accept button, and perhaps even add a little "not enough resources" warning label above or next to it.

There are probably other such issues in the client. If you run into an issue of this sort, it would be great if you can comment on it here so that we may keep track of it.

**Comment by aymericdelab** [comment]
believe it has all been fixed in : https://github.com/BibliothecaDAO/eternum/pull/48
