### ISSUE TITLE
army info not disappearing when hover out

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#390]
army info should disappear once you hover out of the army model, but sometimes, it stays and there's no way to remove it even when hovering in and out again.

<img width="1096" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/ff40e91a-5d51-4976-ae18-fd15b66b9717">

**Comment by r0man1337** [comment]
Can't reproduce. Probably already fixed.
