### ISSUE TITLE
Update armies model

### ISSUE THREAD

**Issue by r0man1337** [BibliothecaDAO/eternum#399]
- [ ] Make different colors for armies of each order
- [ ] Replace model with ship if it's staying on water biomes

**Comment by JeffreyJoel** [comment]
Hi @r0man1337, can I work on this?

**Comment by ponderingdemocritus** [comment]
Hi Jeffery - this is very specific task. However, there are other better first issues if you are looking to contribute. Could you dm me on discord

**Comment by JeffreyJoel** [comment]
Hi @ponderingdemocritus, does this project have a discord server? I currently don't have your discord handle.

**Comment by r0man1337** [comment]
@JeffreyJoel you can find all project links including discord here https://realms.world

**Comment by JeffreyJoel** [comment]
Thank you @r0man1337
