### ISSUE TITLE
Erroneus caravan capacity warning label on "Accept Offer" dialogue

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#40]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/ae66f498-c517-4685-b299-40026d6edca7)

As the image above shows, I get a warning "INCREASE THE AMOUNT OF UNITS" even though 1 unit already has about 33 times the carry capacity to execute a trade of 3kg worth of resources. Something is not right there.

**Comment by aymericdelab** [comment]
fixed in : https://github.com/BibliothecaDAO/eternum/pull/48
