### ISSUE TITLE
Unopened Chests 

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#401]
**Overview**
The current implementation of the game allows players to discover resource chests during exploration, revealing their contents immediately. While this provides instant gratification, it potentially misses an opportunity for adding an element of surprise and strategic depth to the gameplay. 

**Feature Proposal:**
1. Introduction of Unopened Chests:
- Implement a new resource type, "Unopened Chests" (proposed Resource ID: 252). These chests will replace the immediate disclosure of resources in the current system.
- When players discover chests during exploration, they will now receive "Unopened Chests" in their inventory instead of the randomly chosen resource.

2. Gameplay Dynamics:
- Players can choose to either open these chests to discover their contents or keep them unopened for trading purposes.
- Introduce a new function, open_chest, which allows players to open these chests. Upon opening, a chest will yield 20 units of a randomly selected resource.
- The unopened chests, being like any other resources are tradable items. This add a new strategic layer to the game, as players can speculate on the value of the contents or trade them with other players.

3. Resource Weight:
- The weight of an Unopened Chest (Resource ID: 252) should be considered equivalent to 20 times the weight of the resource it contains. 

4. Client:
- Design a distinctive logo or icon for the Unopened Chests to differentiate them from other resources visually.
- Develop an engaging chest-opening animation or experience within the realms view, enhancing the excitement and user engagement when players open these chests.

**Comment by blackmirrordesigner** [comment]
We can add a bit more randomizator into this treasure hunt = have different chests. For example: 
Silver/Gold/Emerald — better chest = better loot = bigger price on the market.
<img width="1269" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/91994843/2101bc74-930a-4f36-8fa5-bcb92fb909c7">
<img width="494" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/91994843/7fb6428b-b47c-44d2-bfad-1656b81265e2">
<img width="456" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/91994843/068eb482-1daa-454a-a5fb-c0dc7dd26a38">

[chests-tinified.zip](https://github.com/BibliothecaDAO/eternum/files/14622308/chests-tinified.zip)

**Comment by aymericdelab** [comment]
great suggestion ! i like it

**Comment by ponderingdemocritus** [comment]
i'm not convinced this is a path we want to take - the exploration reward should mostly be tiny, only occasionally be large.

**Comment by ponderingdemocritus** [comment]
going to close this, we can reopen in the future
