### ISSUE TITLE
When on a Realm and click world map, camera should be on the Realm at the world level

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#405]
Currently when you are on a realm and click world map, it takes you to some arbitrary location.

The camera should be at the location of the Realm you were just viewing.

**Comment by aymericdelab** [comment]
@r0man1337 can you solve this asap ? feels like it would be nice improvement and quick fix

**Comment by r0man1337** [comment]
Fixed in #458
