### ISSUE TITLE
Reduce opacity on decorative elements

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#41]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/dc80e52e-1afc-4be4-a852-f03aa790b388)
These decorative flourishes are nice, but right now they draw too much attention in an already visually busy UI. I would reduce opacity on these elements by roughly 70% to make them compete less with more gameplay-relevant UI elements.

**Comment by r0man1337** [comment]
Fixed in working branch
