### ISSUE TITLE
Minimap 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#412]
a minimap where uses can click and navigate to, rather than panning the world

**Comment by frontboat** [comment]
in

**Comment by frontboat** [comment]
To-Do
- Simple scale slider for map page. (Will likely have to adjust level of details and banner displays at minscale and maxscale)
- interactive Minimap window
- possibly add a "travel or warp" animation upon clicking from minimap

**Comment by PabloVillaplana** [comment]
Hello @ponderingdemocritus  would love to be part of this effort! 👷🏽‍♂️, thanks (I am in OD Hack telegram, ready to start on Monday 🫡)
