### ISSUE TITLE
Improve hex map loading screen

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#457]
When going from realm view to hex map view when clicking on army location, there's a loading screen with a camera move, but it seems like the loading screen finishes too quickly because when it's over, the camera is outside of the map and then moves to the desired location. Also sometimes I can see a 2nd loading screen right after the first one.

**Comment by r0man1337** [comment]
I fixed camera transition in #458, but wasn't able to reproduce 2nd loading screen (probably it's also fixed, but if it's not then please reopen and describe steps to reproduce the bug)
