### ISSUE TITLE
Balance set back to 0 when harvesting food

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#460]
when harvesting food, the amount of food i had in my balance gets replaced by the harvest amount.
Here i had 1.000.000 fish, then only 84 after harvesting. 

<img width="372" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/6bedde9b-a947-4b24-a77a-3f8ac124fea5">

**Comment by ponderingdemocritus** [comment]
this happened to me

**Comment by ponderingdemocritus** [comment]
closing as this being changed
