### ISSUE TITLE
Not possible to attack Realm from map click

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#465]
seems like there's an issue with ui thinking it's a raider when you try attacking the realm by clicking on 3d model. It works through normal Raid component though by clicking on "Attack Realm".
![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/a67aabdf-ee0d-454b-ba03-fc09260c2084)

**Comment by ponderingdemocritus** [comment]
@abanteai-butler
