### ISSUE TITLE
UI Polishing

### ISSUE THREAD

**Issue by r0man1337** [BibliothecaDAO/eternum#49]
- [x] add sounds
- [ ] realm background freezing a bit when executing transactions (can see it when creating an order for example)
- [x] implement the new "Incoming order" component
- [x] create new offer: show correct balances when selecting resources
- [x] create new offer: display loading spinner after creating new offer (similar as in accept offer popup)
- [x] caravans: implement new compnent design from figma
- [x] add notifications
- [ ] implement sorting and filters
- [x] implement "show on map" button
- [x] update Realm popup header to last figma changes
- [x] implement settings and login popups
- [ ] fix github issue from palomato: https://github.com/BibliothecaDAO/eternum/issues/30
- [x] accept offer: balances not showing
- [ ] move queried data to zustand store, to have persisting state between tab switches
- [ ] add "hire caravan" feature, without creating an offer
- [x] disable "Accept" button if you haven't enough resources
- [x] fix warning message logic in creating caravan
- [ ] fix "No Labor" message if you bought only one hour of labor
- [ ] add "pulse animation" placeholders when loading
- [x] make "secondary tabs" sticky to top

**Comment by ponderingdemocritus** [comment]
prioritise gameplay over polish (like sounds)
