### ISSUE TITLE
UI text selectable

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#50]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/a58a7299-9817-426b-ac7b-959c45998d26)

This happens when clicking and dragging on the 3D canvas, passing over an UI element.
We should make it impossible to select anything, basically. There might be exceptions to this eventually, but I can't think of one that currently applies.

**Comment by r0man1337** [comment]
Fixed. Will be applied after update.
