### ISSUE TITLE
[client] Rerender not trigger on level up

### ISSUE THREAD

**Issue by Bal7hazar** [BibliothecaDAO/eternum#500]
While level-uping, the `Labor` > `All` panel is not rerender.

**Expected behavior**

Panel could be rerender on level up

**Screenshots**

https://github.com/BibliothecaDAO/eternum/assets/97087040/5103118f-0d85-491f-a4bc-8912d53bcd0d

**Desktop**

- OS: MacOS
- Browser: Chrome
- Version: 123.0.6312.87

**Comment by ponderingdemocritus** [comment]
good pickup - this is changing in 0.5.0 so going to close as whole thing is refactored
