### ISSUE TITLE
[client] Torii based real time chat

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#502]
Torii server now exposes RTC channels allowing the creation of real time chat.

This task is to replace the current system with torii RTC chat system.

**Comment by Xaxxoo** [comment]
hi @ponderingdemocritus, May I work on this?

**Comment by ponderingdemocritus** [comment]
this is blocked by

https://github.com/dojoengine/dojo.js/pull/178

**Comment by saimeunt** [comment]
@ponderingdemocritus Now that https://github.com/dojoengine/dojo.js/pull/178 is merged I'd like to work on this issue.

I will study how torii RTC channels work and implement it in eternum.

**Comment by saimeunt** [comment]
@ponderingdemocritus Any update on this? Is this still possible to get assigned please?

**Comment by ponderingdemocritus** [comment]
@saimeunt please take this

**Comment by Xaxxoo** [comment]
I asked to take this 3 weeks ago. Lol.
