### ISSUE TITLE
[client] Banking module

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#504]
- [x] AMM Swap
- [x] Bank creation - this happens on world map
- [x] Navigation of banks - within the banking window module
- [x] Management of banks - for owners of the Bank

**Comment by aymericdelab** [comment]
- [ ] add/remove liquidity
- [ ] track your lp + fees
- [ ] deposit/withdraw from your bank account (through caravans)

**Comment by ponderingdemocritus** [comment]
@aymericdelab can you clear and create issues around specific features.
