### ISSUE TITLE
Increase ability to zoom the camera out further.

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#51]
We need to see the entire map on load. 
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/626c61db-35dc-4e12-b4b1-00681786f1f7)
The entire city and all its regions should be visible. This isn't currently the case.
It should also be easy for the player to zoom back out to this overview at any time. Currently, clicking on certain tabs will move the camera in to a region (that's great), and then lock the camera there (not good). The player needs to be able to zoom back out to regain an overview of the whole realm.

**Comment by r0man1337** [comment]
Done.
