### ISSUE TITLE
[client] Fix hexagon noise algo 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#526]

**Comment by Xaxxoo** [comment]
Hi @ponderingdemocritus I would like to take this issue. Could you please assign it to me?

**Comment by ponderingdemocritus** [comment]
@aymericdelab @credence0x not sure status of this. Can you guys update/close if this is working.

If it's huge job, please split and give details.

**Comment by credence0x** [comment]
still relevant. i remember not working on it because someone mentioned that the simplex algo in dojo.js was being rewritten.
was it rewritten? @ponderingdemocritus
