### ISSUE TITLE
[client] Entity Details windows

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#528]
This Module is a button in the main left navigation.

It contains information about the selected Entity.

Since Entities within Eternum can carry resources, and have other functions, this window is generic and dynamic enough to accomodate all Entities.

The high level sections are
- Military Combat (Armies, Battles)
- Commerce (resource information balances)
- Build (can this Entity be built on)

**Comment by Xaxxoo** [comment]
Hi @ponderingdemocritus, may I take this?
