### ISSUE TITLE
[Design] 3d models

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#557]
**Forges - different colours**
- [ ] Copper (4)
- [ ] ColdIron (8)
- [ ] Ignium (15)
- [ ] Gold (9)
- [ ] Silver (6)

**Precious Mines - different colours**
- [ ] Diamonds (11)
- [ ] Sapphire (12)
- [ ] Ruby (13)
- [ ] DeepCrystal (14)
- [ ] TwilightQuartz (18)
- [ ] EtherealSilica (16)

**Mines - different colours**
- [x] Stone (2)
- [ ] Coal (3)
- [ ] Obsidian (5)
- [ ] TrueIce (17)

**Timber Mills - different colours**
- [x] Wood (1)
- [ ] Hartwood (10)
- [ ] Ironwood (7)

**Magic - 1 of each**
- [ ] Mithral (21)
- [x] Dragonhide (22)
- [ ] AlchemicalSilver (19)
- [ ] Adamantine (20)

**Structures**
- [x] Banks

**Comment by rvorias** [comment]
Doing forge

**Comment by 0xTeejey** [comment]
Starting the Precious mine
