### ISSUE TITLE
[client + contracts] Intro questing system

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#562]
When players first launch the game, a series of quests should exist that guide the player through the mechanics.

Technically we do this by

1. Custom events in the Contracts tied to a wallet address. Once complete the events send resources/rewards to the entity. 
2. Reflect these events in the client via some window structure.
3. Once events are emitted, the client will no longer show these as incomplete.

**Comment by ponderingdemocritus** [comment]
- [ ] game tour - navigates around the map to shop key UI parts

**Comment by EjembiEmmanuel** [comment]
@ponderingdemocritus can I work on this?
