### ISSUE TITLE
[contracts] Client Paymaster

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#564]
Eternum, and more broadly speaking, any onchain game, is headless. Many clients can exist to service the player base. We can incentivize clients through clever mechanisms, creating a truly decentralized experience. We can implement this within Eternum.

Loot Survivor implemented a mechanism to split the payment of players between parties, incentivizing the creation of alternative clients.

1. % To developers
2. % To 1st, 2nd, 3rd
3. % To the client

This mechanism worked, and 3+ clients now exist in the wild. Eternum will take this mechanism to the World level and generalize it to allow games to build and incorporate it.

**World Paymaster**
Within Eternum there will be opportunities for players to spend Lords to expand the world. When players spend these lords, these lords will be split between the DAO and the players. 

The World Paymaster System is a generic system that accepts an array of Pay structs. The paymaster then forwards the amount of lords to the address, taking 5%. This amount is all tracked in a model.

```rust
struct Pay {
address: felt252
amount: u256
}
```

![image](https://github.com/BibliothecaDAO/eternum/assets/90423308/c135d795-3a80-4ef8-a802-a4b8335e230c)

**Future**
If the paymaster is generic, then other games can easily leverage it, and the expansion of clients in the world continues.

**Comment by NueloSE** [comment]
@ponderingdemocritus kindly assign me this task
