### ISSUE TITLE
[client] Tx stream

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#565]
We need to stream all players transactions in a window. This is helpful for debugging.

- [x] Client Window
- [ ] Store txs in local state (only for the session)
- [x] Stream txs results with pending states
- [ ] Design clean interface showcasing success/failure

If this is generalised enough, it should be included in dojo.js.

**Comment by JeffreyJoel** [comment]
@ponderingdemocritus, can I work on this? I may need a bit more clarity though.
