### ISSUE TITLE
[contracts] Model optimisations

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#572]
Dojo automatically packs models where possible, to minimise storage costs. We need to leverage this as much as possible.

This only happens to the size of a Felt (252 bits),  so where possible we should minimise our models so they are at max 1 felt.

This tasks is to first:

- [ ] Find what can be optimised and present path
- [ ] Execute

**Comment by ebukizy1** [comment]
assign me this task

**Comment by Osatuyi** [comment]
Can I be assigned this task, please?
