### ISSUE TITLE
Mute shortcut button next to settings button

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#58]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/3ffbb962-a887-4c95-9b94-49c4743ac152)

I think muting the game should be very accessible. It's nice to have detailed volume options nested in the settings menu, but I think there should be a top-level shortcut to mute.

**Comment by r0man1337** [comment]
Fixed in #91
