### ISSUE TITLE
"Insufficient resources" alert next to greyed-out "Build" or "Accept" buttons

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#59]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/92c0a6a4-85a0-4ced-9515-5256c84d09ec)
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/156a62ea-e48a-4e6d-9f97-2b7179597872)

The buttons for building things and accepting offers are no longer clickable if the player doesn't have resources. This is good. To improve UX a little further by giving the player more information as to why some options are not available. I suggest the following two improvements:

1. Adding a greyed-out button style. Right now "Build" button doesn't change style when it becomes unclickable, and the "Accept" button turns orange. Orange is better then no colour change, but I would prefer something less vibrant, more grey, to really emphasize that a button is unclickable. A colour like #766756 perhaps. This colour is already used in other places, like in this font and border:
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/60095b91-4492-4ce6-bb84-f85339c7ecc3)

2. Adding a red label next to the greyed-out button that says "Insufficient resources". Similar alerts could be used in other circumstances.

**Comment by r0man1337** [comment]
Fixed in #91
