### ISSUE TITLE
[client] banks swap resource -> lords wrong amount

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#591]
when swapping from lords -> resource in client, it shows the current amount, but when doing the opposite, the client is miscalculating the payout

**Comment by kateberryd** [comment]
Hi @aymericdelab I would like to work on this

**Comment by aymericdelab** [comment]
thanks for proposing your help ! i'll take care of this one but maybe see if there are other issues you can tackle

**Comment by aymericdelab** [comment]
solved
