### ISSUE TITLE
Market filters issues

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#60]
- [ ] 1. Missing filters

Most of the market filters seem to be missing from the UI, currently there are only _Resources_ and _Orders_, but we still need _Travel time_, _Coalition_, _Trade Routes_, and _Trade Ratio_. Also, _Resources_ need to be split up between what you're selling and what you're buying.

Part of previous discord discussion about it: https://discord.com/channels/884211910222970891/989804511868620800/1109796133481488424

How it currently is:

![Filters-current](https://github.com/BibliothecaDAO/eternum/assets/110478008/74e48329-fb6b-4a0b-b9c0-3785784153ed)

UI mock-up with a few more, but still not all filters:

![filters-UI](https://github.com/BibliothecaDAO/eternum/assets/110478008/5e4450cb-e814-4479-b01a-c2c5ef504de9)

- [ ] 2. Marked filter icon

There are also some other minor issues with filters. The marked _X_ icon is supposed to represent when a filter is selected, so players can easily change their existing filters. Right now it shows when a filter menu is open, which serves no purpose since the players don't need a visual cue to know the menu is open; the menu itself takes care of that. This needs to be changed so the _X_ icon only and always appears when that specific filter has one or more options selected.

You can see the filter marked with the _X_ when there's no resource selected, but the menu is open:

![filters-x-marked](https://github.com/BibliothecaDAO/eternum/assets/110478008/d824acfc-9500-4cec-8846-4b12bc1e2fda)

And here you can see the filter unmarked when the menu is closed, but there are resources marked to be filtered:

![filters-x-unmarked](https://github.com/BibliothecaDAO/eternum/assets/110478008/bc034c11-c07f-4678-ae04-8dc7494423c1)

Seeing the purpose of the icon is to show a filter is currently selected, I'd also suggest changing the _X_ icon for a checkmark icon, the alternative version of the two sketched out by Amaro:

![filters-checkmark](https://github.com/BibliothecaDAO/eternum/assets/110478008/7cb89e01-c332-4994-99ab-707aaa2f223b)

- [x] 3. Filters aren't working

Also, the filters do nothing right now, they're purely decorative. When I try to filter offers by resource or Order nothing happens, the list remains the same. We need to implement their functionality.

As can be seen here, I have offers filtered only for Order of Power, however the offer list remains unchanged showing me all offers from all Orders. The same can be replicated with the resource filter:

![filters-order-selected](https://github.com/BibliothecaDAO/eternum/assets/110478008/da571758-2ae8-4200-9eae-5b5cc9fe317d)

**Comment by aymericdelab** [comment]
solved this in #131
