### ISSUE TITLE
[client] cannot use "useDojo" inside Html three js component

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#609]
there's a HoveringContainer component which has three js dreis' Html component. Goal is to have a general component usable everytime we want to showcase data on hover on 3d models.

the issue is that the dojo context isn't accessible inside and i'm getting "The `useDojo` hook must be used within a `DojoProvider`" error.

**Comment by Dprof-in-tech** [comment]
Hello @aymericdelab  and @ponderingdemocritus, I'm Isaac, a fullstack Javascript dev and I would love to work on this task and to contribute my skills to this project
