### ISSUE TITLE
[client] Optimistic Building placement

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#618]
Building placement needs optimistic rendering. Currently there is a delay when placing a building

**Comment by EjembiEmmanuel** [comment]
Hi @ponderingdemocritus I'll love to work on this

**Comment by Dprof-in-tech** [comment]
Hi @ponderingdemocritus , I would love to work on this since @EjembiEmmanuel is busy working on another one

**Comment by ponderingdemocritus** [comment]
@Dprof-in-tech ok please have a go.

You will need to update the optimistic system calls

**Comment by Dprof-in-tech** [comment]
> @Dprof-in-tech ok please have a go.
> 
> You will need to update the optimistic system calls

Ok then Chief. Please assign me to it though while I work on it
