### ISSUE TITLE
[client chore] useMemo sweep

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#657]
Sweep all useEffects and convert to useMemo where possible to save memory. There is some lag in production version, and this is low hanging fruit.

**Comment by r0man1337** [comment]
@ponderingdemocritus can you provide steps to reproduce issue? I can try to research what it caused by

**Comment by ponderingdemocritus** [comment]
Nothing in particular - but where possible we need to memo everything and not use useEffect as the memory stacks up quickly
