### ISSUE TITLE
Occasionally actions, when successful, aren't reflected in the UI

### ISSUE THREAD

**Issue by clicksave** [BibliothecaDAO/eternum#658]
**Describe the bug** A clear and concise description of what the bug is.

Encountered this issue where I'd create a farm, the transaction would be successful but the model wouldn't appear until refresh. Saw the same issue when claiming my starting material

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/BibliothecaDAO/eternum/assets/3332646/806a61bd-b3ef-4859-a2f8-2f8852ca1caa

Captured in the video above. button is selected but doesn't enter a default state

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Arc + Chrome

**Comment by ponderingdemocritus** [comment]
This is a torii bug
