### ISSUE TITLE
Notifications menu

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#66]
Eternum needs a notification menu. The game is feature rich, meaning there'll be a lot going on at all times, and it's played in a real time, competitive multiplayer environment, meaning losing track of any relevant information may result in significant damage to your Realms. Thus, gameplay-relevant information must always be highlighted and delivered to the player in a pronounced, prominent way, and this way is the notifications menu.

- The notifications menu is player-based, and will deliver only the information relevant for that specific player's empire. It'll have two versions: one with notifications pertaining only a specific Realm (standard setting in the Realms map), and one with notifications pertaining multiples Realms (standard setting showing all Realms in your wallet, in the world map). 

- Additionally, a configurations menu should allow the player to customize whichever version of notifications they want to see where, e.g. if the player wants to see notifications for all Realms when in the Realms map or even if they want to pick and choose from their Realms. Ideally that could manifest as a toggle button to show notifications for all Realms even in the Realms map, with the addition of an option to checkmark specific Realms to be shown in notifications. The configurations menu should also have a toggle for dropdowns menus in notifications (show them opened or the default, closed).

- Notifications should not only be closable/dismissible, but new notifications should also be highlighted in the list to indicate they're new. The highlight can be done several ways: background, borders, colours, glow, among others. A new notifications loses its highlight once the player passes the mouse over it.

- Notifications can also be pinned and unpinned.

- Notifications' heading will redirect the player to the respective UI menu for that information.

A first mock-up was already made couple months ago:

<img width="466" alt="notifications-mockup" src="https://github.com/BibliothecaDAO/eternum/assets/110478008/044e78dd-533f-4336-8e88-97bfd8abdd1c">

Below is the list of notifications needed, with the caveat that as more game systems are implemented into the game (Banking, Crafting, etc.) the list of notifications needed will also expand. The list contains the information for both notification menu types: single Realm and multiple Realms.

- [ ] Offer accepted.
For every time a standing offer is accepted. Notification heading redirects to the Offers menu.

- Single Realm version:
Contains simply the text "Offer accepted" and nothing else. A dropdown menu will show resources sent, resources received (both individually), Merchants in Caravan, partner Realm, and real time distance remaining in hours.

- Multiple Realms versions:
Same as single Realm, with the addition of the Realm name in the heading by the side of "Offer accepted".

- [ ] Offer proposed. 
For every time someone proposes an offer directly to your Realm. Notification heading redirects to the Offers menu.

- Single Realm version:
Contains simply the text "Offer proposed" and nothing else. A dropdown menu will show resources sent, resources received (both individually), carry capacity needed, partner Realm, and travel distance in hours.

- Multiple Realms versions:
Same as single Realm, with the addition of the Realm name in the heading by the side of "Offer proposed".

- [ ] Caravan Arrived.
For every time a Caravan arrives in your Realm. Notification heading redirects to the offers menu, and claim button doesn't redirect, but instantaneously claims the arrived resources. The button greys out and becomes "Claimed" after.

- Single Realm version:
Contains the text "Caravan arrived" and a "Claim resources" button at the end of the heading space. A dropdown menu will show resources sent, resources received (both individually), Merchants in Caravan, and partner Realm.

- Multiple Realms versions:
Same as single Realm, with the addition of the Realm name in the heading by the side of "Caravan arrived".

- [ ] Labour finished.
For every time labour production expires on any of the unique resources. Notification heading and button redirect to the labour menu, opening the employ labour/buy tools section for that specific resource.

- Single Realm version:
Contains the text "_Coal_ labour finished" (with Coal being replaced by the respective resource name)  and a "Buy more" button at the end of the heading space. There's no dropdown menu.

- Multiple Realms versions:
Same as single Realm, with the addition of the Realm name in the heading by the side of "_Coal_ labour finished".

- [ ] Food buildings expired.
For every time farms or fisheries expire. Notification heading and button redirect to the food buildings menu, opening the build section for that specific resource.

- Single Realm version:
Contains the text "_Farm_ expired" (with Farm being replaced by the Fishery, when applicable) and a "Build more" button at the end of the heading space. There's no dropdown menu.

- Multiple Realms versions:
Same as single Realm, with the addition of the Realm name in the heading by the side of "_Farm_ expired".

**Comment by ponderingdemocritus** [comment]
This is all great - i'm going to take this

**Comment by r0man1337** [comment]
Just created base layout for notifications with different types. Commits in **feat/notifications** branch. 
Going to add transitions and content templates.

**Comment by r0man1337** [comment]
@ponderingdemocritus I added layout & transitions for notifications component + few examples.
You can pull it from my working branch.
