### ISSUE TITLE
[client] biome

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#665]
![Screenshot 2024-05-02 at 18 48 49](https://github.com/BibliothecaDAO/eternum/assets/90423308/fbe1402c-d30d-4ed2-b935-87e00dcf7dc0)

**Comment by Jemiiah** [comment]
Can i work on this project @ponderingdemocritus

**Comment by edisontim** [comment]
I think a good way to go to solve this is to add a check for undefined before using the biomes and if the hex is non-existent, get rid of the hex search params in the URL and send back to the login page.
