### ISSUE TITLE
[cairo] tests interface

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#671]
interfaces have all changed from an interface.cairo file to the contracts.cairo file of it's system. Most tests are still not updated with this change so they cannot run.  Most tests have been commented out for now. 

Goal: sozo test should be able to run the tests even if they don't yet pass

**Comment by ponderingdemocritus** [comment]
I think we should align on how we write systems and code structure as we move into 0.6.0 and clean up and standadise things. We need to make it approachable for new contributors, and modders.

**Comment by Ayoazeez26** [comment]
Can I work on this @aymericdelab ?

**Comment by cwastche** [comment]
@credence0x Are you still working on this issue ? Could I help with this in some capacity ?

**Comment by aymericdelab** [comment]
@cwastche yes please take this issue
