### ISSUE TITLE
Add colours to Tailwind to allow for JIT

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#68]
`{/* IDK why, but tailwind cant handle dynamic custom classes if they wasnt used before */}`

@r0man1337 you need to add them to tailwind config in order for them to be included

**Comment by r0man1337** [comment]
Related info (need to add colors to safelist):
https://stackoverflow.com/questions/67289894/jit-tailwindcss-using-variable-in-bg-not-rendering-color
