### ISSUE TITLE
[client] Add other entity select 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#686]
This should allow one way transferring to any entity. Currently only shows the users.

![Screenshot 2024-05-06 at 18 24 18](https://github.com/BibliothecaDAO/eternum/assets/90423308/d06e0167-8ee3-4325-b909-7d4d205f8d8b)

**Comment by aymericdelab** [comment]
i'm thinking maybe we could group that between "My Realms", "Other Realms", "Banks" etc ?
