### ISSUE TITLE
Incorrect Realm Map Coordinates

### ISSUE THREAD

**Issue by credence0x** [BibliothecaDAO/eternum#697]
Realm Map has inconsistent coordinate system with world map and contracts

when you run this
```
    let mut start = Coord { x: 4, y: 4};
    print!("\n {} \n", start.neighbor(Direction::East));
    print!("\n {} \n", start.neighbor(Direction::NorthEast));
    print!("\n {} \n", start.neighbor(Direction::NorthWest));
    print!("\n {} \n", start.neighbor(Direction::West));
    print!("\n {} \n", start.neighbor(Direction::SouthWest));
    print!("\n {} \n", start.neighbor(Direction::SouthEast));
```

the result should be 
```
 Coord (x:5, y:4)  
 Coord (x:5, y:5)  
 Coord (x:4, y:5)  
 Coord (x:3, y:4)  
 Coord (x:4, y:3)  
 Coord (x:5, y:3)  
```
this is not the case for the realm map

**Comment by ponderingdemocritus** [comment]
The hex system between contract and client is different in this case

**Comment by aymericdelab** [comment]
i wonder if issue doesn't come from this line here:
https://github.com/BibliothecaDAO/eternum/blob/b5622ba9764a37b881222dd33a0252d0548394bf/client/src/hooks/helpers/useHexPosition.tsx#L61

**Comment by aymericdelab** [comment]
was able to poinpoint the issue, when creating the hexception grid, cols should have an offset of 1 for every odd row like this:
current:
```
      positions.push({
        ...getUIPositionFromColRow(_col + shifted.col, _row + shifted.row, true),
        z: 0.315,
        color: _color,
        col: _col + shifted.col,
        row: _row + shifted.row,
        startOffset: startOffset,
      });
```
should be this:
```
      const col = _col + shifted.col + (_row % 2 === 0 ? 0 : 1);
      positions.push({
        ...getUIPositionFromColRow(_col + shifted.col, _row + shifted.row, true),
        z: 0.315,
        color: _color,
        col,
        row: _row + shifted.row,
        startOffset: startOffset,
      });
```

**Comment by aymericdelab** [comment]
the issue then is that getUIPositionFromColRow wrongly computes the position in the UI for every preview and built building like this: 
so that even if my mouse is hovering over 5:5 here, it shows the building on 6:5, and when i build it, the result will be shown in 6:5. Even though in the contract state it is on 5:5. 
<img width="605" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/48d5df3c-e26a-44b4-82b9-aa555bdd0fbb">

**Comment by aymericdelab** [comment]
i think it's best that @r0man1337 takes a look at this when he's back
