### ISSUE TITLE
UI menus blocking each other

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#70]
Currently menus have fixed places on-screen, meaning when you open several of them they appear in the same place atop of each other:

![ui-menus-stacking](https://github.com/BibliothecaDAO/eternum/assets/110478008/055ff471-40a1-48e4-aeeb-b0f3f4162335)

While some of these menus don't need to be used together, some of them do, thus this menu stacking is an issue. There are several ways to solve this, a solution I thought of was to simply have the first submenu opening at the top left, and then having each subsequent menu opening below the last one until the end of the screen, and then beginning a new column by the right.  That would probably require some adjustment of submenu sizes to make some dimensions are a bit more standardized. 

What do you think @r0man1337?

**Comment by r0man1337** [comment]
Please check out #144
