### ISSUE TITLE
[client] Market balance is incorrect 

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#713]
![Screenshot 2024-05-10 at 08 18 30](https://github.com/BibliothecaDAO/eternum/assets/90423308/f3fca247-7701-4f92-a414-d727fcf3bf23)

Market balance is based off the raw balance, not the production balance

**Comment by Jemiiah** [comment]
@ponderingdemocritus is this work up for grab?
