### ISSUE TITLE
Custom resource icons

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#73]
As previously discussed, we need to make custom resource icons. To repeat something I previously said in [discord](https://discord.com/channels/884211910222970891/989804511868620800/1109796173490962442): the minimalist ones we have now are hard to memorize and thus not very user friendly since you need to consult a reference sheet to keep up with them.

Wood, coal, silver, gold, copper, all gems... several of our resources have imagery that's very identifiable and should make for instantly recognizable icons. And for the completely fantastical/made up resources it shouldn't be hard to create something unique in colour and shape that makes them very identifiable too - you look at it once, you remember.

**Comment by Amaro-Koberle** [comment]
I agree this will be necessary, but it is low-priority right now. With over 20 different resources, we kinda have to include the name often anyway (whenever there is space, or in a tooltip), even if we have the most recognizable of icons.

**Comment by Fomentador** [comment]
@Amaro-Koberle 

We're in the shipping stage of the trading milestone, everything low-priority and meant for polish was relegated to be done in this stage. As discussed in meetings, the idea is that we do all the polish needed to deliver the final intended user experience and don't need to come back to this in the future. We then move to the next development milestone to implement new systems and features.

With that said, if you still believe icons shouldn't be done in this milestone you can close this Issue.
