### ISSUE TITLE
fish decreasing even without production

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#739]
Since silver and cold iron are missing from the balance, Ironwood isn't getting produced, the only resource that I have in my balance still gets consumed by it though

<img width="991" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/9f6ddea7-4804-40c4-af75-99047ff9b370">

**Comment by cwastche** [comment]
It seems that the same problem applies to Wheat as well. Could I get assigned to this ?

**Comment by ponderingdemocritus** [comment]
@credence0x did you last PR solve this?

**Comment by aymericdelab** [comment]
after discussing with @credence0x this seems to be totally normal contract wise, players will need to pay attention to this. In UI I prevent people from building something where not all inputs are > 0 and also added a warning sign next to resource if something was consuming without producing. I think we can thus close issue.
