### ISSUE TITLE
Tooltip information

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#74]
Every non-obvious element should contain tooltips, players should know the function of everything without having to leave the game screen. There are some clear cases where tooltips are missing/partially implemented, like for resources:

Resource name appears when hovering mouse over stored resources.

![resource-hover-implemented](https://github.com/BibliothecaDAO/eternum/assets/110478008/a7dd9d94-33fd-4b88-8056-5e87779fc53c)

But they do not appear when hovering mouse over resources on market.

![resource-hover-not-implemented](https://github.com/BibliothecaDAO/eternum/assets/110478008/f6fa9949-5daf-494c-94d6-b31f14616f93)

Besides these cases of partial implementation, there are also plenty of places where tooltips are needed in order to explain to the player what that specific feature/section/button does, necessary for providing an uninterrupted play session, easy on-boarding of new players, and seamless user experience. List below:

- [x] Every resource icon in the client should display the respective resource name as a tooltip.
- [x] Every Order icon in the client should display the respective Order name as a tooltip.
- [x] Labour menu icon should display "Manage all of your Realm resource production here."
- [x] Resources sub-menu icon should display "Look at your current production, or increase it by buying labour or buildings. Don't forget to harvest your resources."
- [x] Trade menu icon should display "No Realm is self-sufficient. Trade with other Lords to get the resources you need."
- [x] Offers sub-menu icon should display "Create new offers or examine offers made exclusively to you. Watch as offers are executed, and claim your resources when they arrive."
- [x] Market sub-menu icon should display "Offers from all over the world are found here. Trade with your fellow Lords."
- [x] Caravans sub-menu icon should display "You can only trade resources if there are Caravans to carry them. Manage your Caravans here."

There are more tooltips to be added that involve changes to current client. Once these changes are implemented more tooltips will be added to this list or introduced through other GitHub Issues (as is already the case for some).

**Comment by r0man1337** [comment]
Added in #116
