### ISSUE TITLE
[client] new travel/explore for armies doesn't seem to be working

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#742]
not possible to select any hex when clicking on explore with the army

<img width="666" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/0a04f6bf-6a2c-4b7d-a251-8c5f9657d67b">

**Comment by ponderingdemocritus** [comment]
are you sure? this was working. The highlight may be too subtle

**Comment by aymericdelab** [comment]
I’ll try again to make sure

**Comment by aymericdelab** [comment]
closing this
