### ISSUE TITLE
not enough weight when depositing from army to realm

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#755]
Realms should have infinite capacity so it's weird that it's failing with "not enough weight"

![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/b42c09cd-06c4-49cd-98c3-f1be05bf11db)

**Comment by edisontim** [comment]
This assert happens when the army's actual weight is lower than the amount you're trying to transfer, I assume this assert happens because you minted resources directly into the army's inventory
Changing the assert's message to be a bit more explicit but otherwise the behavior's correct :)
