### ISSUE TITLE
[contracts] Build over max population capacity

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#769]
**Describe the bug** You can pass max capacity when spawning a new building at 4/5 or 5/5 pop. Once you pass this cap (6/5), the population checks are correctly being executed though.

**To Reproduce** Steps to reproduce the behavior:

Checkout at commit 3ac2d3a4f0d015f92fde1735404c36487292b11e (The following commit adds a checker in the UI. However, this should not restrict a user from calling the contract directly afaik.)

1. Create two ressource buildings (4/5 pop)
2. Create a third ressource building (6/5 pop)

1. Create two ressource buildings (4/5 pop)
2. Create two economic buildings (6/5 pop)

Note: When at 5/5 pop, you can create an economic building but not a ressource building

**Screenshots** 
<img width="111" alt="Screenshot 2024-05-15 at 15 32 15" src="https://github.com/BibliothecaDAO/eternum/assets/80072466/9fa068b8-487f-4408-a8a8-4e76aa332b2b">

**Comment by ponderingdemocritus** [comment]
i belive this is contract error missing a check
