### ISSUE TITLE
Minimizing menu windows

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#77]
This feature is necessary primarily because of the chat menu: it has 0 gameplay utility and for most people it's something they'll just want to check occasionally - some won't check it at all. Right now it's a locked feature occupying a huge part of the screen, blocking actual relevant gameplay information in the Realms map. To remedy that, I suggest we add a feature to minimize this menu, providing the option to remove it from the screen while still remaining easily accessible. It can remain as an icon by the side of the screen while minimized, like this:

![chat-minimized](https://github.com/BibliothecaDAO/eternum/assets/110478008/4131eead-9fb4-4ad5-866a-6e8616d7dae8)

Although other menus are significantly more relevant and less intrusive, players still may want to minimize them eventually for a better view of the different screens. Thus, the minimize feature should be implemented in all UI menus (currently chat menu, Realm menu and notifications menu).

**Comment by r0man1337** [comment]
Added in #116
