### ISSUE TITLE
Direct offers

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#78]
As [previously discussed](https://discord.com/channels/884211910222970891/989804511868620800/1110587255422202008), players must be able to create direct offers to a single Realm. This should follow the same flow that creating an open offers does, with the single difference that a field to introduce a Realm address should be available. 

This would require the addition of the following UI elements:

- [ ] A field to input taker Realm in the _creating offer_ menu. A possible implementation is a toggle with "Open Offer" (default) and "Direct Offer" as the options. When a player switches the toggle to "Direct offer" a field for "Realm number" appears. Player then just inputs a Realm number between 1 - 8000 and creates the offer.
- [ ] The partner Realm name displayed for the individual offer in "My offers" tab. In order to preserve space, it can be a simple "To: Realm" text.
- [ ] An identifier for each individual offer in "My offers" tab to differentiate open and direct offers. The text for direct offers can be the one above and for open offers simply an "Open" text.

@aymericdelab assigning you too since this is a function of the contract, so it'll probably require Cairo input for integration.

**Comment by aymericdelab** [comment]
resolved in #136, just need to polish a bit the UI to make it look better
