### ISSUE TITLE
Districts integration missing

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#79]
Some districts in the Realms model (ranch, labour and market to be exact) are already integrated with the client, being reactive to mouse hovers and displaying information, although some functionalities are still missing. There are entire districts, however, that still need to be integrated. To be implemented:

- [x] Not only clicking on the respective UI menus should zoom the camera to the each map district, but the other way around should happen as well - it's in fact the more important reason for this feature. Players should be able to easily open the respective UI menus in order to do actions by simply clicking in the corresponding map district. For instance, when a player clicks on the Market district, the camera should zoom in on the district and open the Market UI menu so that the player can manage the game systems represented by that area.
- [x] Fisheries need to be integrated. Their menu redirect would be the the resource list showing current fish production stats with the sub-menu for building fisheries opened at the side. 
- [x] Farms need to be integrated. Their menu redirect would be the the resource list showing current wheat production stats with the sub-menu for building farms opened at the side.

**Comment by r0man1337** [comment]
Implemented in #116
