### ISSUE TITLE
[Testing] Missing system contracts tests

### ISSUE THREAD

**Issue by cwastche** [BibliothecaDAO/eternum#797]
List of missing system tests

- [ ] Bank
  - [ ] Bank
  * fn open_account
    - Bank does not exist
    - Bank account already opened
  * fn create_bank
  * fn change_owner_fee
  
  - [ ] Liquidity
    * fn add
      - bad bank account
      - bad resource balance
      - bad lords amount
     * fn remove
       - bad shares amount
  - [ ] swap
     * internal fns
- [ ] Buildings
- [ ] Combat
- [ ] Config
- [ ] Dev ?
- [x] Hyperstructure
- [x] Leveling
   - [x] InternalLeveling
      * fn level up
        - level up past max level config
 - [ ]  Map
   * internal fn explore
     - already explored tile
   * fn pay_food_and_get_explore_reward
     - assert burned resources
- [ ]  Name
- [x]  Realm
  * fn mint_starting_resources 
    - test as entity other than realms
    - claim twice with 1 realm
- [ ] Resources
- [ ] Trade
- [ ] Transport
  - [ ] road_systems
    * test_insufficient_balance
  - [ ] travel_systems
  - [ ] donkey_systems
- [ ] Utils

**Comment by aymericdelab** [comment]
@credence0x could you take a look at why contracts are not running correctly and also make sure all the ones that exist currently run without failure ?

**Comment by ponderingdemocritus** [comment]
can this be closed @credence0x ? lets update to more precise issue

**Comment by credence0x** [comment]
yeah let's close it
