### ISSUE TITLE
Sliders in resource production

### ISSUE THREAD

**Issue by Fomentador** [BibliothecaDAO/eternum#80]
Currently the sub-menus to buy resources have a field to input the number of items to be bought with arrows to increase or decrease the amount:

![buy-resources](https://github.com/BibliothecaDAO/eternum/assets/110478008/95063728-e0ac-409b-8447-f1767a4bdad0)

When the input is limited between a small range - like food buildings work right now - an UI interface like the above isn't a problem since it provides players the tools to quickly find the amount of items they want to buy. In the case of tools and labour, however, it doesn't.

Tools and labour don't have any limit for how much of it can be bought in one go and they won't be always bought at similar amounts. Someone might buy a month of labour for one resource and only a day for another, for instance, depending on the funding they have and their specific needs. When dealing with large amounts the arrow functionality is useless, since increasing or decreasing labour units by small amounts would take a long time, and inputting the number directly would require from the player a lengthy process of trial and error by inputting different numbers until they find the amount they want. 

Thus, the current input field for resource production should be replaced by a field that uses a slider instead of arrows. Not only does this solve all the above problems, but it also better informs the player about how much resources they have available to buy any specific labour. If someone wants to buy coal labour, for instance, they can instantly know the labour amount that'll cost 30%, 50%, or 100% of their resources by moving the slider around, since the max range for the slider will be determined by the max quantity of vault resources that can afford that labour production.

A slider icon would look like this, with the design be adjusted for the client, of course:

![resources-slider](https://github.com/BibliothecaDAO/eternum/assets/110478008/8b0a8b92-3722-406c-a5d3-d8c8fbd0333e)

**Comment by r0man1337** [comment]
Good point.

**Comment by ponderingdemocritus** [comment]
have assigned @r0man1337
