### ISSUE TITLE
[client] multiple quests issues

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#819]
- [ ] when you click on "resources claim" (1st quest), there is a lag where the loading of the button stops and you can still click on it.
- [ ] Same with all other resources claim on 2nd quest.
- [ ] difference between quests left and number shown next to character on bottom navigation (only 3 quests left, but number next to character on bottom shows 4)
- [ ] when placing a resource factory, quest does not get updated, need to refresh to show update

![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/bc248122-348c-4985-9d60-6692846de9f1)
![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/c806cce2-a2b8-4b29-bcde-7dab90cb6c72)
![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/c708a441-b068-4b37-a0b3-064222356a5b)

**Comment by Ajith27887** [comment]
@aymericdelab Can I do this?
