### ISSUE TITLE
[client] same button for travel/explore

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#829]
when you click on army, you need to then click on travel OR explore. The player shouldn't have to click on either, and just click on where it wants to move on the map. Then based on if it's explored or not the UI can assume exploration or travel

**Comment by r0man1337** [comment]
We can show tooltip with info instead of action button.
Like if you hovering over unexplored hex you will see this text: "Click to explore: -50 %resource name%".
And if hex is explored you will see other text: "Click to travel: -5 stamina"

**Comment by aymericdelab** [comment]
that would be cool
