### ISSUE TITLE
[client] bottom army card occupies the bottom 1/5th of screen 

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#940]
**Describe the bug**  bottom army card occupies the bottom 1/5th of screen 
When an army is selected, you can't click most of the bottom of the screen 

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="1440" alt="Screenshot 2024-06-15 at 03 42 09" src="https://github.com/BibliothecaDAO/eternum/assets/76473430/31ad6513-5895-4032-875d-e376d6aaafd7">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by ponderingdemocritus** [comment]
have removed
