### ISSUE TITLE
[client] Leave battle button showing up even if I don't have army in battle

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#959]
This is a battle completely unrelated to me but it seems like the "leave battle" shows up

<img width="642" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/d33cd6c3-a0d4-4745-bf52-cded6056aa57">

**Comment by edisontim** [comment]
This will be fixed with the merging of my branch

**Comment by aymericdelab** [comment]
awesome
