### ISSUE TITLE
[client] Claimed structure still not owned by me

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#960]
I have claimed the structure which didn't have any defence, but it still seems to owned by someone else. Even after rerfesh. I can protect it though. 

<img width="996" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/eb2d1598-7568-4ba2-8cd7-95a447939877">

**Comment by ponderingdemocritus** [comment]
is this resolved?

**Comment by edisontim** [comment]
Yes, was solved by #952
