### ISSUE TITLE
[idea] Since you've been gone...

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#971]
A popup showing the user what has happened since the last time they logged.

- Resources generated
- Raided
- Battles won
- Mines stolen
- Hyperstructures stolen
- Points generated

etc...

**Comment by edisontim** [comment]
Did you have an idea of how to do this? Thinking of having a timestamp in local storage (updates every 10 secs or so when user is connected), then fetch relevant events since that timestamp on next connection. We'll need to add a bunch of events in the contracts then
