### ISSUE TITLE
Show that elements have not yet been confirmed on node

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#98]
**Is your feature request related to a problem? Please describe.**
We use optimistic rendering for the game so we already show the result of a transaction in the client before it's confirmed. But the user does not know if that result is definitive or not. 

**Describe the solution you'd like**
It would be better UX to show the user the info but also add some sort of sign/logo/loading somewhere that shows that it has not yet been confirmed.

I was thinking also to have the data blinking until it's settled. Something that would look like this:
https://media.geeksforgeeks.org/wp-content/uploads/20200609161317/screen-capture-11.gif

**Comment by ponderingdemocritus** [comment]
I agree loading state is needed in some areas, but sometimes I think optimistic is fine, and it reverts if fails.

Perhaps we have expose a loading bool on every execute, which can be used

**Comment by ponderingdemocritus** [comment]
has this been actioned?

**Comment by aymericdelab** [comment]
not yet
