### ISSUE TITLE
[bot] New app - Discussion

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/eternum#982]
One of the largest aspects of this game is combat. Right now the only way to know if you have been attacked is if you login to the application.

We can design a helpful bot that runs and tracks information and pushes to the user on discord/telegram.

My current thinking is the following:

**Honoapi + postgres**
- This is basic CRUD and stores the users account
- Polls the graphql for updates and then sends to users where events match
- Enriches the information with an LLM and provides deep lore. We could also pipe these events into a vector db to create interesting history.

**Questions:**
- My thinking is that we define an Events schema and inject these into the contracts where we want to send updates.

**Example:**
- Combat started -> contains attacker, defender, location
- Combat reinforced
- Combat withdraw
- Seiged Location
- Pillaged Resources

**Comment by edisontim** [comment]
Would be super down to work on this

**Comment by ponderingdemocritus** [comment]
Yes that would be the plan. This also probably bundles up with #971 , which is still open for disucssion.
