### ISSUE TITLE
Trade offers are not visible to other realms

### ISSUE THREAD

**Issue by Freakazoid78tr** [BibliothecaDAO/eternum#987]
I created a bunch of trade offers for copper from one of my realms (Nganu).. But when I log out of it and log in to another realm I settled (Muki Kaki), I can't see any of those copper offers. Is that normal?  Below are the copper market view from 2 different realms I settled. 

![image](https://github.com/BibliothecaDAO/eternum/assets/102276968/80e4903a-87af-41f8-93f0-03166ce3fe00)

![image](https://github.com/BibliothecaDAO/eternum/assets/102276968/32fdb93c-670e-4184-b7a3-e07f57e0b09b)

**Comment by ponderingdemocritus** [comment]
this was network issue

closing
